<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>
                K&#xFC;nstler
            </th>
            <th>
                Titel
            </th>
            <th>
                Genre
            </th>
            <th>
                Jahr
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                a-ha
            </td>
            <td>
                Foot Of The Mountain
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                A-Teens
            </td>
            <td>
                Mama Mia
            </td>
            <td>
                2010er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Achim Reichel
            </td>
            <td>
                Aloha Heja He
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Adriano Celentano
            </td>
            <td>
                Azzuro
            </td>
            <td>
                Italienische Musik &#x26; Italo-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                &#xC4;rzte
            </td>
            <td>
                Westerland
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Alan Parsons Project
            </td>
            <td>
                Eye In The Sky
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Alcazar
            </td>
            <td>
                Crying At The Discotheque
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Andreas Bourani
            </td>
            <td>
                Alles Nur In Meinem Kopf
            </td>
            <td>
                2010er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                BAP
            </td>
            <td>
                Verdamp Lang Her
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Barry Manilow
            </td>
            <td>
                Copacabana
            </td>
            <td>
                Englischer Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Beatles
            </td>
            <td>
                Ob-la-di Ob-la-da
            </td>
            <td>
                1960er Beat &#x26; Flower Power
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Black
            </td>
            <td>
                Everything&#x27;s Coming Up Roses
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bob Dylan
            </td>
            <td>
                Knockin&#x27; On Heaven&#x27;s Door
            </td>
            <td>
                1960er Beat &#x26; Flower Power
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bronski Beat
            </td>
            <td>
                Smalltown Boy
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bruce Springsteen
            </td>
            <td>
                I&#x27;m On Fire
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bryan Adams
            </td>
            <td>
                Run To You
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bryan Adams
            </td>
            <td>
                Somebody
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Bryan Adams
            </td>
            <td>
                Summer Of &#x27;69
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                C.C.R.
            </td>
            <td>
                Bad Moon Rising
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                C.C.R.
            </td>
            <td>
                Hey Tonight
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Cliff Richard
            </td>
            <td>
                Dreamin&#x27;
            </td>
            <td>
                Englischer Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Cliff Richard
            </td>
            <td>
                Rote Lippen Soll Man K&#xFC;ssen
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Costa Cordalis
            </td>
            <td>
                Anita
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Daft Punk
            </td>
            <td>
                Get Lucky
            </td>
            <td>
                2010er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Depeche Mode
            </td>
            <td>
                Enjoy The Silence
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Dire Straits
            </td>
            <td>
                Sultans Of Swing
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                DJ &#xD6;tzi
            </td>
            <td>
                Anton Aus Tirol
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
                1999
            </td>
        </tr>
        <tr>
            <td>
                Doris Day
            </td>
            <td>
                Whatever Will Be Will Be (Que Sera Sera)
            </td>
            <td>
                1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Eagles
            </td>
            <td>
                Take It Easy
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Elton John
            </td>
            <td>
                Sacrifice
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Elvis Presley
            </td>
            <td>
                Always On My Mind
            </td>
            <td>
                1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Elvis Presley
            </td>
            <td>
                Are You Lonesome Tonight
            </td>
            <td>
                1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Elvis Presley
            </td>
            <td>
                Devil In Disguise
            </td>
            <td>
                1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Eric Clapton
            </td>
            <td>
                Lay Down Sally
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
                1977
            </td>
        </tr>
        <tr>
            <td>
                Eric Clapton
            </td>
            <td>
                Promises
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
                1977
            </td>
        </tr>
        <tr>
            <td>
                Eric Clapton
            </td>
            <td>
                Tears In Heaven
            </td>
            <td>
                Jazz &#x26; Hintergrundmusik (Dinner, Lounge)
            </td>
            <td>
                1992
            </td>
        </tr>
        <tr>
            <td>
                Eric Clapton
            </td>
            <td>
                Wonderful Tonight
            </td>
            <td>
                Jazz &#x26; Hintergrundmusik (Dinner, Lounge)
            </td>
            <td>
                1977
            </td>
        </tr>
        <tr>
            <td>
                Fiction Factory
            </td>
            <td>
                Feels Like Heaven
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
                1985
            </td>
        </tr>
        <tr>
            <td>
                Frank Sinatra
            </td>
            <td>
                Strangers In The Night
            </td>
            <td>
                Jazz &#x26; Hintergrundmusik (Dinner, Lounge)
            </td>
            <td>
                1966
            </td>
        </tr>
        <tr>
            <td>
                Fugees
            </td>
            <td>
                Killing Me Softly
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Gibson Brothers
            </td>
            <td>
                Que Sera Mi Vida
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Gottlieb Wendehals
            </td>
            <td>
                Polon&#xE4;se Blankenese
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Hans Albers
            </td>
            <td>
                Auf Der Reeperbahn Nachts Um Halb Eins
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
                1943
            </td>
        </tr>
        <tr>
            <td>
                Heinz-Rudolf Kunze
            </td>
            <td>
                Dein Ist Mein Ganzes Herz
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Heroes del Silencio
            </td>
            <td>
                Entre Dos Tierras
            </td>
            <td>
                Spanischer Gitarren-Rock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Howard Carpendale
            </td>
            <td>
                Hello Again
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Joachim Witt
            </td>
            <td>
                Goldener Reiter
            </td>
            <td>
                Neue Deutsche Welle (NDW)
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                John Denver
            </td>
            <td>
                Country Roads
            </td>
            <td>
                Country Music
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                John Paul Young
            </td>
            <td>
                Love Is In The Air
            </td>
            <td>
                Englischer Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Katrina &#x26; The Waves
            </td>
            <td>
                Walking On Sunshine
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Keimzeit
            </td>
            <td>
                Kling Klang
            </td>
            <td>
                Ostrock (DDR)
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Kiss
            </td>
            <td>
                I Was Made For Loving You
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Klaus Lage Band
            </td>
            <td>
                1000 und 1 Nacht (Zoom!)
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Klaus-Renft-Combo
            </td>
            <td>
                Apfeltraum
            </td>
            <td>
                Ostrock (DDR)
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Londonbeat
            </td>
            <td>
                I&#x27;ve Been Thinking About You
            </td>
            <td>
                1990er Rock-Pop &#x26; Independent
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Lost Frequencies feat. Janieck Devy
            </td>
            <td>
                Reality
            </td>
            <td>
                2010er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Louis Armstrong
            </td>
            <td>
                Moonriver
            </td>
            <td>
                Englischer Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Louis Armstrong
            </td>
            <td>
                What A Wonderful World
            </td>
            <td>
                Englischer Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Marius M&#xFC;ller-Westernhagen
            </td>
            <td>
                Willenlos
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Mavericks
            </td>
            <td>
                Foolish Heart
            </td>
            <td>
                1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Men At Work
            </td>
            <td>
                Who Can It Be Now
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Moby
            </td>
            <td>
                Lift Me Up
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
                2005
            </td>
        </tr>
        <tr>
            <td>
                M&#xFC;nchener Freiheit
            </td>
            <td>
                Herzschlag Ist Der Takt
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                M&#xFC;nchener Freiheit
            </td>
            <td>
                Tausendmal Du
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Nek
            </td>
            <td>
                Laura Non C&#x27;e
            </td>
            <td>
                Italienische Musik &#x26; Italo-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Nick Kamen
            </td>
            <td>
                I Promised Myself
            </td>
            <td>
                1990er Rock-Pop &#x26; Independent
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Nick Straker Band
            </td>
            <td>
                A Walk In The Park
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Paul Kuhn
            </td>
            <td>
                Es Gibt Kein Bier Auf Hawaii
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
                1963
            </td>
        </tr>
        <tr>
            <td>
                Peter Maffay
            </td>
            <td>
                Eiszeit
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Peter Maffay
            </td>
            <td>
                Tiefer
            </td>
            <td>
                Deutschrock
            </td>
            <td>
                1989
            </td>
        </tr>
        <tr>
            <td>
                Phil &#x26; John
            </td>
            <td>
                Hello Mary Lou
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Phil Collins
            </td>
            <td>
                You&#x27;ll Be In My Heart
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Philipp Dittberner &#x26; Marv
            </td>
            <td>
                Wolke 4
            </td>
            <td>
                2010er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Police
            </td>
            <td>
                Every Breath You Take
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Puhdys
            </td>
            <td>
                Alt Wie Ein Baum
            </td>
            <td>
                Ostrock (DDR)
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Purple Schulz
            </td>
            <td>
                Du Hast Mir Gerade Noch Gefehlt
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Purple Schulz
            </td>
            <td>
                Kleine Seen
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Rainhard Fendrich
            </td>
            <td>
                Macho Macho
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Ricky Nelson
            </td>
            <td>
                Hello Mary Lou
            </td>
            <td>
                Country Music
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Robbie Williams
            </td>
            <td>
                Angels
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Roy Orbison
            </td>
            <td>
                I Drove All Night
            </td>
            <td>
                1990er Rock-Pop &#x26; Independent
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Rudi Schuricke
            </td>
            <td>
                Capri Fischer
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Scott Mc Kenzie
            </td>
            <td>
                San Francisco
            </td>
            <td>
                1960er Beat &#x26; Flower Power
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Simply Red
            </td>
            <td>
                Something Got Me Started
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Soulsister
            </td>
            <td>
                The Way To Your Heart
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Sportfreunde Stiller
            </td>
            <td>
                Ein Kompliment
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Steinwolke
            </td>
            <td>
                Katharine Katharine
            </td>
            <td>
                Neue Deutsche Welle (NDW)
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Tom Petty
            </td>
            <td>
                I Won&#x27;t Back Down
            </td>
            <td>
                1990er Rock-Pop &#x26; Independent
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Tom Petty
            </td>
            <td>
                Learning To Fly
            </td>
            <td>
                1990er Rock-Pop &#x26; Independent
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Toto
            </td>
            <td>
                Africa
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Toto
            </td>
            <td>
                Child&#x27;s Anthem
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo J&#xFC;rgens
            </td>
            <td>
                Aber Bitte Mit Sahne
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo J&#xFC;rgens
            </td>
            <td>
                Griechischer Wein
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo J&#xFC;rgens
            </td>
            <td>
                Ich War Noch Niemals In New York
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo J&#xFC;rgens
            </td>
            <td>
                Mit 66 Jahren
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo J&#xFC;rgens
            </td>
            <td>
                Wilde Kirschen
            </td>
            <td>
                Schlager
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Udo Lindenberg
            </td>
            <td>
                Mein Ding
            </td>
            <td>
                Deutschrock
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Ultravox
            </td>
            <td>
                Dancing With Tears In My Eyes
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Village People
            </td>
            <td>
                Y.M.C.A.
            </td>
            <td>
                1970er Rock &#x26; Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Volkslied
            </td>
            <td>
                Kufsteiner Lied
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Volkslied
            </td>
            <td>
                Rosamunde
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Volkslied
            </td>
            <td>
                What Shall We Do With The Drunken Sailor
            </td>
            <td>
                Volksmusik &#x26; Stimmungsmusik
            </td>
            <td>
            </td>
        </tr>
    </tbody>
</table>
