<main>
    <div>
        <h2>
            1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1960er Beat &#x26; Flower Power
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1970er Rock &#x26; Pop
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1980er Rock-Pop &#x26; Synthi Pop
        </h2>
        <ol>
            <li>
                Alan Parsons Project - Eye In The Sky
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                Elton John - Sacrifice
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1990er Rock-Pop &#x26; Independent
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            2000er Rock-Pop
        </h2>
        <ol>
            <li>
                Alcazar - Crying At The Discotheque
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            2000er Rock-Pop
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Chanson
        </h2>
        <ol>
        </ol>
    </div>
    <div>
        <h2>
            Country Music
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Deutschrock
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Englischer Schlager
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Neue Deutsche Welle (NDW)
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Ostrock
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Schlager
        </h2>
        <ol>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
            <li>
                TODO - TODO
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Volksmusik &#x26; Stimmungsmusik
        </h2>
        <ol>
        </ol>
    </div>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
    <ERROR_MISSING_TAG_NAME>
    </ERROR_MISSING_TAG_NAME>
</main>
