<main>
    <div>
        <h2>
            1950er Rock &#x27;n&#x27; Roll &#x26; Rockabilly
        </h2>
        <ol>
            <li>
                Doris Day - Whatever Will Be Will Be (Que Sera Sera)
            </li>
            <li>
                Elvis Presley - Always On My Mind
            </li>
            <li>
                Elvis Presley - Are You Lonesome Tonight
            </li>
            <li>
                Elvis Presley - Devil In Disguise
            </li>
            <li>
                Mavericks - Foolish Heart
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1960er Beat &#x26; Flower Power
        </h2>
        <ol>
            <li>
                Beatles - Ob-la-di Ob-la-da
            </li>
            <li>
                Bob Dylan - Knockin&#x27; On Heaven&#x27;s Door
            </li>
            <li>
                Scott Mc Kenzie - San Francisco
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1970er Rock &#x26; Pop
        </h2>
        <ol>
            <li>
                C.C.R. - Bad Moon Rising
            </li>
            <li>
                C.C.R. - Hey Tonight
            </li>
            <li>
                Eagles - Take It Easy
            </li>
            <li>
                Eric Clapton - Lay Down Sally
            </li>
            <li>
                Eric Clapton - Promises
            </li>
            <li>
                Village People - Y.M.C.A.
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1980er Rock-Pop &#x26; Synthi Pop
        </h2>
        <ol>
            <li>
                Alan Parsons Project - Eye In The Sky
            </li>
            <li>
                Black - Everything&#x27;s Coming Up Roses
            </li>
            <li>
                Bronski Beat - Smalltown Boy
            </li>
            <li>
                Bruce Springsteen - I&#x27;m On Fire
            </li>
            <li>
                Bryan Adams - Run To You
            </li>
            <li>
                Bryan Adams - Somebody
            </li>
            <li>
                Bryan Adams - Summer Of &#x27;69
            </li>
            <li>
                Depeche Mode - Enjoy The Silence
            </li>
            <li>
                Dire Straits - Sultans Of Swing
            </li>
            <li>
                Elton John - Sacrifice
            </li>
            <li>
                Fiction Factory - Feels Like Heaven
            </li>
            <li>
                Gibson Brothers - Que Sera Mi Vida
            </li>
            <li>
                Katrina &#x26; The Waves - Walking On Sunshine
            </li>
            <li>
                Kiss - I Was Made For Loving You
            </li>
            <li>
                Men At Work - Who Can It Be Now
            </li>
            <li>
                Nick Straker Band - A Walk In The Park
            </li>
            <li>
                Police - Every Breath You Take
            </li>
            <li>
                Soulsister - The Way To Your Heart
            </li>
            <li>
                Toto - Africa
            </li>
            <li>
                Toto - Child&#x27;s Anthem
            </li>
            <li>
                Ultravox - Dancing With Tears In My Eyes
            </li>
        </ol>
    </div>
    <div>
        <h2>
            1990er Rock-Pop &#x26; Independent
        </h2>
        <ol>
            <li>
                Londonbeat - I&#x27;ve Been Thinking About You
            </li>
            <li>
                Nick Kamen - I Promised Myself
            </li>
            <li>
                Roy Orbison - I Drove All Night
            </li>
            <li>
                Tom Petty - I Won&#x27;t Back Down
            </li>
            <li>
                Tom Petty - Learning To Fly
            </li>
        </ol>
    </div>
    <div>
        <h2>
            2000er Rock-Pop
        </h2>
        <ol>
            <li>
                a-ha - Foot Of The Mountain
            </li>
            <li>
                Alcazar - Crying At The Discotheque
            </li>
            <li>
                Fugees - Killing Me Softly
            </li>
            <li>
                Moby - Lift Me Up
            </li>
            <li>
                Phil Collins - You&#x27;ll Be In My Heart
            </li>
            <li>
                Robbie Williams - Angels
            </li>
            <li>
                Simply Red - Something Got Me Started
            </li>
            <li>
                Sportfreunde Stiller - Ein Kompliment
            </li>
        </ol>
    </div>
    <div>
        <h2>
            2010er Rock-Pop
        </h2>
        <ol>
            <li>
                A-Teens - Mama Mia
            </li>
            <li>
                Andreas Bourani - Alles Nur In Meinem Kopf
            </li>
            <li>
                Daft Punk - Get Lucky
            </li>
            <li>
                Lost Frequencies feat. Janieck Devy - Reality
            </li>
            <li>
                Philipp Dittberner &#x26; Marv - Wolke 4
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Country Music
        </h2>
        <ol>
            <li>
                John Denver - Country Roads
            </li>
            <li>
                Ricky Nelson - Hello Mary Lou
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Deutschrock
        </h2>
        <ol>
            <li>
                Achim Reichel - Aloha Heja He
            </li>
            <li>
                &#xC4;rzte - Westerland
            </li>
            <li>
                BAP - Verdamp Lang Her
            </li>
            <li>
                Heinz-Rudolf Kunze - Dein Ist Mein Ganzes Herz
            </li>
            <li>
                Klaus Lage Band - 1000 und 1 Nacht (Zoom!)
            </li>
            <li>
                Marius M&#xFC;ller-Westernhagen - Willenlos
            </li>
            <li>
                M&#xFC;nchener Freiheit - Herzschlag Ist Der Takt
            </li>
            <li>
                M&#xFC;nchener Freiheit - Tausendmal Du
            </li>
            <li>
                Peter Maffay - Eiszeit
            </li>
            <li>
                Peter Maffay - Tiefer
            </li>
            <li>
                Purple Schulz - Du Hast Mir Gerade Noch Gefehlt
            </li>
            <li>
                Purple Schulz - Kleine Seen
            </li>
            <li>
                Rainhard Fendrich - Macho Macho
            </li>
            <li>
                Udo Lindenberg - Mein Ding
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Englischer Schlager
        </h2>
        <ol>
            <li>
                Barry Manilow - Copacabana
            </li>
            <li>
                Cliff Richard - Dreamin&#x27;
            </li>
            <li>
                John Paul Young - Love Is In The Air
            </li>
            <li>
                Louis Armstrong - Moonriver
            </li>
            <li>
                Louis Armstrong - What A Wonderful World
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Franz&#xF6;sischer Rock-Pop &#x26; Chanson
        </h2>
        <ol>
        </ol>
    </div>
    <div>
        <h2>
            Italienische Musik &#x26; Italo-Pop
        </h2>
        <ol>
            <li>
                Adriano Celentano - Azzuro
            </li>
            <li>
                Nek - Laura Non C&#x27;e
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Jazz &#x26; Hintergrundmusik (Dinner, Lounge)
        </h2>
        <ol>
            <li>
                Eric Clapton - Tears In Heaven
            </li>
            <li>
                Eric Clapton - Wonderful Tonight
            </li>
            <li>
                Frank Sinatra - Strangers In The Night
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Neue Deutsche Welle (NDW)
        </h2>
        <ol>
            <li>
                Joachim Witt - Goldener Reiter
            </li>
            <li>
                Steinwolke - Katharine Katharine
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Ostrock (DDR)
        </h2>
        <ol>
            <li>
                Keimzeit - Kling Klang
            </li>
            <li>
                Klaus-Renft-Combo - Apfeltraum
            </li>
            <li>
                Puhdys - Alt Wie Ein Baum
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Polnischer Rock-Pop
        </h2>
        <ol>
        </ol>
    </div>
    <div>
        <h2>
            Schlager
        </h2>
        <ol>
            <li>
                Cliff Richard - Rote Lippen Soll Man K&#xFC;ssen
            </li>
            <li>
                Costa Cordalis - Anita
            </li>
            <li>
                Gottlieb Wendehals - Polon&#xE4;se Blankenese
            </li>
            <li>
                Howard Carpendale - Hello Again
            </li>
            <li>
                Phil &#x26; John - Hello Mary Lou
            </li>
            <li>
                Rudi Schuricke - Capri Fischer
            </li>
            <li>
                Udo J&#xFC;rgens - Aber Bitte Mit Sahne
            </li>
            <li>
                Udo J&#xFC;rgens - Griechischer Wein
            </li>
            <li>
                Udo J&#xFC;rgens - Ich War Noch Niemals In New York
            </li>
            <li>
                Udo J&#xFC;rgens - Mit 66 Jahren
            </li>
            <li>
                Udo J&#xFC;rgens - Wilde Kirschen
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Spanischer Gitarren-Rock
        </h2>
        <ol>
            <li>
                Heroes del Silencio - Entre Dos Tierras
            </li>
        </ol>
    </div>
    <div>
        <h2>
            Volksmusik &#x26; Stimmungsmusik
        </h2>
        <ol>
            <li>
                DJ &#xD6;tzi - Anton Aus Tirol
            </li>
            <li>
                Hans Albers - Auf Der Reeperbahn Nachts Um Halb Eins
            </li>
            <li>
                Paul Kuhn - Es Gibt Kein Bier Auf Hawaii
            </li>
            <li>
                Volkslied - Hoch Auf Dem Gelben Wagen
            </li>
            <li>
                Volkslied - Kufsteiner Lied
            </li>
            <li>
                Volkslied - Rosamunde
            </li>
            <li>
                Volkslied - What Shall We Do With The Drunken Sailor
            </li>
        </ol>
    </div>
</main>
