<table class="table table-striped table-bordered table-hover table-condensed">
    <thead>
        <tr>
            <th>
                Titel
            </th>
            <th>
                K&#xFC;nstler
            </th>
            <th>
                Genre
            </th>
            <th>
                Jahr
            </th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                Eye In The Sky
            </td>
            <td>
                Alan Parsons Project
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Crying At The Discotheque
            </td>
            <td>
                Alcazar
            </td>
            <td>
                2000er Rock-Pop
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td>
                Sacrifice
            </td>
            <td>
                Elton John
            </td>
            <td>
                1980er Rock-Pop &#x26; Synthi Pop
            </td>
            <td>
            </td>
        </tr>
    </tbody>
</table>
