/*
 * Copyright (C) 1999-2023. Christian Heller.
 *
 * This file is part of the Cybernetics Oriented Interpreter (CYBOI).
 *
 * CYBOI is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * CYBOI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CYBOI. If not, see <http://www.gnu.org/licenses/>.
 *
 * Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
 * CYBOP Developers <cybop-developers@nongnu.org>
 *
 * @version CYBOP 0.25.0 2023-03-01
 * @author Christian Heller <christian.heller@cybop.org>
 */

//
// CAUTION! Do NOT edit this file in directory "src".
// It is autogenerated and its content will be overwritten during make.
// See template in file "build/cmake_config.h.in"!
//

#ifndef CYBOP_CMAKE_CONFIG_H
#define CYBOP_CMAKE_CONFIG_H

#define PROJECT_NAME L"cybop"
#define INTERPRETER_NAME L""
#define PROJECT_VERSION  L"0.26.0"
#define COPYRIGHT_INFO  L""

/* CYBOP_CMAKE_CONFIG_H */
#endif
