# CAUTION! Do NOT write directory names with a slash "/" at the end.
# If doing so, the directory names would be added twice,
# e.g. "cybop/examples/examples/" which is NOT wanted.
EXTRA_DIST = doc/books/cybol/cybol_2013-05-16.html doc/books/cybol/cybol.css doc/books/cybop/cybop.pdf doc/manual/manual-en.pdf examples AUTHORS autogen.sh ChangeLog configure.ac COPYING INSTALL Makefile.am NEWS README

SUBDIRS = src
