#
# Copyright (C) 1999-2014. Christian Heller.
#
# This file specifies directories and files to be considered in the build process.
#
# Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
# CYBOP Developers <cybop-developers@nongnu.org>
#
# @version CYBOP 0.16.0 2014-03-31
# @author Didier Link <didier@famille-link.fr>
# @author Christian Heller <christian.heller@tuxtax.de>
#

# CAUTION! Do NOT write directory names with a slash "/" at the end.
# If doing so, the directory names would be added twice,
# e.g. "cybop/examples/examples/" which is NOT wanted.
EXTRA_DIST = doc/books/cybol/cybol_2013-05-16.html doc/books/cybol/cybol.css doc/books/cybop/cybop.pdf doc/manual/manual-en.pdf examples AUTHORS autogen.sh ChangeLog configure.ac COPYING INSTALL Makefile.am NEWS README

SUBDIRS = src
