#
# $RCSfile: cybol.ebnf,v $
#
# Copyright (c) 2003-2004. Christian Heller and the CYBOP developers.
#
# Permission is granted to copy, distribute and/or modify this document
# under the terms of the GNU Free Documentation License, Version 1.1
# or any later version published by the Free Software Foundation;
# with no Invariant Sections, with no Front-Cover Texts and with no Back-Cover
# Texts. A copy of the license is included in the section entitled
# 'GNU Free Documentation License'.
#
# http://www.cybop.net
# - Cybernetics Oriented Programming -
#
# @version $Revision: 1.3 $ $Date: 2005/07/14 10:31:40 $ $Author: christian $
# @author Christian Heller <christian.heller@tuxtax.de>
#

CYBOL       = '<node>'
                  {node}
              '</node>';

node        = '<node ' all_attribute '\>' |
              '<node ' all_attribute '>'
                  {node}
              '</node>';

all_attribute           = attribute_name attribute_channel attribute_format attribute_model

attribute_name          = 'name="' name '"';
attribute_channel       = 'channel="' channel '"';
attribute_format        = 'format="' format '"';
attribute_model         = 'model="' model '"';

name            = description;
channel         = description;
format          = description | mime_type_separator;
model           = value;

description     = { ( letter | number ) };
value           = { ( letter | number | full_stop | comma | plus | minus | asterisk | solidus | number_sign ) };

knowledge_path_separator    = full_stop | number_sign;
mime_type_separator         = solidus;

letter          = small_letter | big_letter;
small_letter    = 'a' | 'b' | 'c' | 'd' | 'e' | 'f' | 'g' |
                  'h' | 'i' | 'j' | 'k' | 'l' | 'm' | 'n' |
                  'o' | 'p' | 'q' | 'r' | 's' | 't' | 'u' |
                  'v' | 'w' | 'x' | 'y' | 'z';
big_letter      = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' |
                  'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' |
                  'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' |
                  'V' | 'W' | 'X' | 'Y' | 'Z';

number          = '0' | '1' | '2' | '3' | '4' |
                  '5' | '6' | '7' | '8' | '9';

full_stop       = '.';
comma           = ',' | '+' | '-' | '*';
plus            = ',' | '+' | '-' | '*';
minus           = ',' | '+' | '-' | '*';
asterisk        = ',' | '+' | '-' | '*';
solidus         = '/';
number_sign     = '#';
