################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/attr.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/autostatic.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/barrier.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/cancel.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/cleanup.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/condvar.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/create.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/dll.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/errno.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/exit.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/fork.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/global.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/misc.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/mutex.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/nonportable.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/private.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getdetachstate.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getinheritsched.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedparam.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedpolicy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getscope.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstackaddr.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstacksize.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setdetachstate.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setinheritsched.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedparam.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedpolicy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setscope.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstackaddr.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstacksize.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_wait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_getpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_setpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cancel.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_signal.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_wait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_getpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_setpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_delay_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_detach.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_equal.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_exit.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getconcurrency.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getschedparam.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getspecific.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getunique_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getw32threadhandle_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_join.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_create.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_delete.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_kill.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_consistent.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_lock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_timedlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_trylock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_unlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getkind_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getrobust.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_gettype.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setkind_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setrobust.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_settype.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_num_processors_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_once.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_rdlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedrdlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedwrlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_tryrdlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_trywrlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_unlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_wrlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_getpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_setpshared.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_self.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcancelstate.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcanceltype.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setconcurrency.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setschedparam.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setspecific.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_lock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_trylock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_unlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_testcancel.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_timechange_handler_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_win32_attach_detach_np.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_MCS_lock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_OLL_lock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_callUserDestroyRoutines.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_calloc.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_cond_check_need_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_getprocessors.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_is_attr.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_mutex_check_need_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_new.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processInitialize.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processTerminate.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_relmillisecs.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_reuse.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_cancelwrwait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_check_need_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_semwait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_spinlock_check_need_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadDestroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadStart.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_throw.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_timespec.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocCreate.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocDestroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/rwlock.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_max.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_min.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_getscheduler.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_setscheduler.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_yield.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_close.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_destroy.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_getvalue.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_init.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_open.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post_multiple.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_timedwait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_trywait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_unlink.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_wait.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/semaphore.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/signal.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/spin.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/sync.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tsd.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/w32_CancelableWait.c 

OBJS += \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/attr.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/autostatic.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/barrier.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/cancel.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/cleanup.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/condvar.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/create.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/dll.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/errno.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/exit.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/fork.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/global.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/misc.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/mutex.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/nonportable.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/private.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getdetachstate.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getinheritsched.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedparam.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedpolicy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getscope.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstackaddr.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstacksize.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setdetachstate.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setinheritsched.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedparam.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedpolicy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setscope.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstackaddr.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstacksize.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_wait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_getpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_setpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cancel.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_signal.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_wait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_getpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_setpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_delay_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_detach.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_equal.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_exit.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getconcurrency.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getschedparam.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getspecific.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getunique_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getw32threadhandle_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_join.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_create.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_delete.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_kill.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_consistent.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_lock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_timedlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_trylock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_unlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getkind_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getrobust.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_gettype.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setkind_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setrobust.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_settype.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_num_processors_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_once.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_rdlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedrdlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedwrlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_tryrdlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_trywrlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_unlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_wrlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_getpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_setpshared.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_self.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcancelstate.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcanceltype.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setconcurrency.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setschedparam.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setspecific.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_lock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_trylock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_unlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_testcancel.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_timechange_handler_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_win32_attach_detach_np.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_MCS_lock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_OLL_lock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_callUserDestroyRoutines.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_calloc.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_cond_check_need_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_getprocessors.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_is_attr.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_mutex_check_need_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_new.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processInitialize.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processTerminate.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_relmillisecs.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_reuse.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_cancelwrwait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_check_need_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_semwait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_spinlock_check_need_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadDestroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadStart.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_throw.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_timespec.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocCreate.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocDestroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/rwlock.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_max.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_min.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_getscheduler.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_setscheduler.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_yield.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_close.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_destroy.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_getvalue.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_init.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_open.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post_multiple.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_timedwait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_trywait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_unlink.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_wait.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/semaphore.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/signal.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/spin.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sync.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tsd.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/w32_CancelableWait.o 

C_DEPS += \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/attr.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/autostatic.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/barrier.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/cancel.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/cleanup.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/condvar.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/create.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/dll.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/errno.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/exit.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/fork.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/global.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/misc.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/mutex.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/nonportable.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/private.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getdetachstate.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getinheritsched.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedparam.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getschedpolicy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getscope.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstackaddr.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_getstacksize.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setdetachstate.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setinheritsched.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedparam.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setschedpolicy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setscope.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstackaddr.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_attr_setstacksize.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrier_wait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_getpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_barrierattr_setpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cancel.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_signal.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_cond_wait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_getpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_condattr_setpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_delay_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_detach.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_equal.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_exit.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getconcurrency.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getschedparam.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getspecific.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getunique_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_getw32threadhandle_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_join.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_create.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_key_delete.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_kill.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_consistent.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_lock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_timedlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_trylock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutex_unlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getkind_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_getrobust.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_gettype.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setkind_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_setrobust.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_mutexattr_settype.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_num_processors_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_once.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_rdlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedrdlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_timedwrlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_tryrdlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_trywrlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_unlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlock_wrlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_getpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_rwlockattr_setpshared.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_self.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcancelstate.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setcanceltype.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setconcurrency.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setschedparam.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_setspecific.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_lock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_trylock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_spin_unlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_testcancel.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_timechange_handler_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/pthread_win32_attach_detach_np.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_MCS_lock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_OLL_lock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_callUserDestroyRoutines.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_calloc.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_cond_check_need_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_getprocessors.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_is_attr.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_mutex_check_need_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_new.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processInitialize.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_processTerminate.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_relmillisecs.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_reuse.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_cancelwrwait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_rwlock_check_need_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_semwait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_spinlock_check_need_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadDestroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_threadStart.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_throw.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_timespec.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocCreate.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/ptw32_tkAssocDestroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/rwlock.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_max.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_get_priority_min.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_getscheduler.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_setscheduler.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sched_yield.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_close.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_destroy.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_getvalue.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_init.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_open.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_post_multiple.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_timedwait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_trywait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_unlink.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sem_wait.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/semaphore.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/signal.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/spin.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/sync.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tsd.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/w32_CancelableWait.d 


# Each subdirectory must supply rules for building sources it contributes
trunk/include/visualstudio/pthreadsw32/pthreads.2/%.o: ../trunk/include/visualstudio/pthreadsw32/pthreads.2/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


