################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier6.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchlib.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6a.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6d.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel7.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel8.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel9.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup0.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2_1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar6.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar7.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar8.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar9.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/context1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/count1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/detach1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/equal1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/errno1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/eyal1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/inherit1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join0.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/kill1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/loadfree.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1n.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6es.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6n.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6rs.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6s.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7n.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8e.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8n.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8r.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/openmp1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2_t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3_t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4_t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5_t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock7.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock8.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4t.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore5.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sequence1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sizes.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin3.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin4.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/stress1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd2.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid1.c \
../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid2.c 

OBJS += \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier6.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchlib.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6a.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6d.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel7.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel8.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel9.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup0.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2_1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar6.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar7.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar8.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar9.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/context1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/count1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/detach1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/equal1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/errno1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/eyal1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/inherit1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join0.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/kill1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/loadfree.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1n.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6es.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6n.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6rs.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6s.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7n.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8e.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8n.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8r.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/openmp1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2_t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3_t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4_t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5_t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock7.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock8.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4t.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore5.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sequence1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sizes.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin3.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin4.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/stress1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd2.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid1.o \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid2.o 

C_DEPS += \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/barrier6.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchlib.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/benchtest5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6a.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel6d.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel7.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel8.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cancel9.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup0.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/cleanup3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar1_2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar2_1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar3_3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar6.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar7.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar8.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/condvar9.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/context1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/count1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/create3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/delay2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/detach1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/equal1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/errno1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exception3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/exit5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/eyal1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/inherit1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join0.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/join3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/kill1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/loadfree.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1n.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex1r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex2r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex3r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6es.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6n.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6rs.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex6s.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7n.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex7r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8e.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8n.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/mutex8r.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/once4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/openmp1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/priority2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/reuse2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/robust5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock2_t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock3_t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock4_t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock5_t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock6_t2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock7.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/rwlock8.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/self2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore4t.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/semaphore5.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sequence1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/sizes.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin3.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/spin4.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/stress1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tryentercs2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/tsd2.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid1.d \
./trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/valid2.d 


# Each subdirectory must supply rules for building sources it contributes
trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/%.o: ../trunk/include/visualstudio/pthreadsw32/pthreads.2/tests/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


