;***************************************************************************************************
;************************ ########          ######    **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ########         ###  ###   **********************************************
;************************ ##     ###       ########   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ########         ###  ###   **********************************************
;***************************************************************************************************

[Default]
elementsFile = /home/pit/develop/cybop/tools/cybol_generator/widget/elements.xml
