################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
trunk/src/windows \
trunk/src/variable/type_size \
trunk/src/variable \
trunk/src/tester \
trunk/src/tester/variable/type_size \
trunk/src/tester/executor/memoriser \
trunk/src/tester/executor/manipulator \
trunk/src/tester/executor/manipulator/integer \
trunk/src/tester/executor \
trunk/src/tester/executor/caster \
trunk/src/tester/executor/caster/basic/double \
trunk/src/tester/executor/calculator \
trunk/src/tester/executor/calculator/basic/pointer \
trunk/src/tester/executor/calculator/basic/integer \
trunk/src/tester/controller \
trunk/src/tester/applicator \
trunk/src/logger \
trunk/src/language \
trunk/src/executor/searcher/selector/xml \
trunk/src/executor/searcher/selector/xdt/record \
trunk/src/executor/searcher/selector/xdt \
trunk/src/executor/searcher/selector/xdt/field \
trunk/src/executor/searcher/selector/xdt/bdt \
trunk/src/executor/searcher/selector/uri \
trunk/src/executor/searcher/selector/uri/http \
trunk/src/executor/searcher/selector/percent_encoding \
trunk/src/executor/searcher/selector/knowledge \
trunk/src/executor/searcher/selector/http_response \
trunk/src/executor/searcher/selector/http_request_uri \
trunk/src/executor/searcher/selector/http_request \
trunk/src/executor/searcher/selector/cybol \
trunk/src/executor/searcher/selector/command_line \
trunk/src/executor/searcher/selector/character_reference \
trunk/src/executor/searcher/selector/authority \
trunk/src/executor/searcher/selector/ansi_escape_code \
trunk/src/executor/searcher/name_finder \
trunk/src/executor/searcher/mover \
trunk/src/executor/searcher/finder \
trunk/src/executor/searcher/detector \
trunk/src/executor/runner \
trunk/src/executor/representer \
trunk/src/executor/representer/serialiser/xml \
trunk/src/executor/representer/serialiser/xdt_field_description \
trunk/src/executor/representer/serialiser/xdt \
trunk/src/executor/representer/serialiser/xdt/field \
trunk/src/executor/representer/serialiser/xdt/duration/yyyy \
trunk/src/executor/representer/serialiser/xdt/duration/hhmmhhmm \
trunk/src/executor/representer/serialiser/xdt/duration/ddmmyyyyddmmyyyy \
trunk/src/executor/representer/serialiser/xdt/datetime/qyyyy \
trunk/src/executor/representer/serialiser/xdt/datetime/mmyy \
trunk/src/executor/representer/serialiser/xdt/datetime/ddmmyyyy \
trunk/src/executor/representer/serialiser/x_window_system \
trunk/src/executor/representer/serialiser/win32_display \
trunk/src/executor/representer/serialiser/win32_console \
trunk/src/executor/representer/serialiser/user_interface \
trunk/src/executor/representer/serialiser/tui \
trunk/src/executor/representer/serialiser/time_scale/weekday \
trunk/src/executor/representer/serialiser/time_scale/running_day \
trunk/src/executor/representer/serialiser/time_scale/julian_date \
trunk/src/executor/representer/serialiser/time_scale/julian_calendar \
trunk/src/executor/representer/serialiser/time_scale/gregorian_calendar \
trunk/src/executor/representer/serialiser/terminal_mode \
trunk/src/executor/representer/serialiser/percent_encoding \
trunk/src/executor/representer/serialiser/model_diagram \
trunk/src/executor/representer/serialiser/layout \
trunk/src/executor/representer/serialiser/latex \
trunk/src/executor/representer/serialiser/http_response \
trunk/src/executor/representer/serialiser/http_request \
trunk/src/executor/representer/serialiser/html \
trunk/src/executor/representer/serialiser/gui \
trunk/src/executor/representer/serialiser/gui/shape \
trunk/src/executor/representer/serialiser/cybol \
trunk/src/executor/representer/serialiser/cybol/integer \
trunk/src/executor/representer/serialiser/cybol/fraction/vulgar \
trunk/src/executor/representer/serialiser/cybol/fraction/decimal \
trunk/src/executor/representer/serialiser/cybol/duration/si \
trunk/src/executor/representer/serialiser/cybol/duration/julian \
trunk/src/executor/representer/serialiser/cybol/duration/jd \
trunk/src/executor/representer/serialiser/cybol/duration/iso \
trunk/src/executor/representer/serialiser/cybol/datetime/utc \
trunk/src/executor/representer/serialiser/cybol/datetime/ti \
trunk/src/executor/representer/serialiser/cybol/datetime/tai \
trunk/src/executor/representer/serialiser/cybol/datetime/posix \
trunk/src/executor/representer/serialiser/cybol/datetime/julian \
trunk/src/executor/representer/serialiser/cybol/datetime/jd \
trunk/src/executor/representer/serialiser/cybol/datetime/gregorian \
trunk/src/executor/representer/serialiser/cybol/complex/polar \
trunk/src/executor/representer/serialiser/cybol/complex/cartesian \
trunk/src/executor/representer/serialiser/cybol/colour \
trunk/src/executor/representer/serialiser/cybol/boolean \
trunk/src/executor/representer/serialiser/character_reference \
trunk/src/executor/representer/serialiser/ansi_escape_code \
trunk/src/executor/representer/deserialiser/xml \
trunk/src/executor/representer/deserialiser/xdt \
trunk/src/executor/representer/deserialiser/xdt/record \
trunk/src/executor/representer/deserialiser/xdt/ldt \
trunk/src/executor/representer/deserialiser/xdt/gdt \
trunk/src/executor/representer/deserialiser/xdt/field \
trunk/src/executor/representer/deserialiser/xdt/duration/yyyy \
trunk/src/executor/representer/deserialiser/xdt/duration/hhmmhhmm \
trunk/src/executor/representer/deserialiser/xdt/duration/ddmmyyyyddmmyyyy \
trunk/src/executor/representer/deserialiser/xdt/datetime/qyyyy \
trunk/src/executor/representer/deserialiser/xdt/datetime/mmyy \
trunk/src/executor/representer/deserialiser/xdt/datetime/ddmmyyyy \
trunk/src/executor/representer/deserialiser/xdt/bdt \
trunk/src/executor/representer/deserialiser/win32_console \
trunk/src/executor/representer/deserialiser/uri \
trunk/src/executor/representer/deserialiser/uri/http \
trunk/src/executor/representer/deserialiser/tui \
trunk/src/executor/representer/deserialiser/time_scale/running_day \
trunk/src/executor/representer/deserialiser/time_scale/julian_date \
trunk/src/executor/representer/deserialiser/time_scale/julian_calendar \
trunk/src/executor/representer/deserialiser/time_scale/gregorian_calendar \
trunk/src/executor/representer/deserialiser/time_scale/correction \
trunk/src/executor/representer/deserialiser/percent_encoding \
trunk/src/executor/representer/deserialiser/latex \
trunk/src/executor/representer/deserialiser/knowledge \
trunk/src/executor/representer/deserialiser/http_response \
trunk/src/executor/representer/deserialiser/http_request_uri \
trunk/src/executor/representer/deserialiser/http_request \
trunk/src/executor/representer/deserialiser/html \
trunk/src/executor/representer/deserialiser/gui \
trunk/src/executor/representer/deserialiser/cybol \
trunk/src/executor/representer/deserialiser/cybol/integer \
trunk/src/executor/representer/deserialiser/cybol/fraction/vulgar \
trunk/src/executor/representer/deserialiser/cybol/fraction/decimal \
trunk/src/executor/representer/deserialiser/cybol/duration/si \
trunk/src/executor/representer/deserialiser/cybol/duration/julian \
trunk/src/executor/representer/deserialiser/cybol/duration/jd \
trunk/src/executor/representer/deserialiser/cybol/duration/iso \
trunk/src/executor/representer/deserialiser/cybol/datetime/utc \
trunk/src/executor/representer/deserialiser/cybol/datetime/ti \
trunk/src/executor/representer/deserialiser/cybol/datetime/tai \
trunk/src/executor/representer/deserialiser/cybol/datetime/posix \
trunk/src/executor/representer/deserialiser/cybol/datetime/julian \
trunk/src/executor/representer/deserialiser/cybol/datetime/jd \
trunk/src/executor/representer/deserialiser/cybol/datetime/gregorian \
trunk/src/executor/representer/deserialiser/cybol/complex/polar \
trunk/src/executor/representer/deserialiser/cybol/complex/cartesian \
trunk/src/executor/representer/deserialiser/cybol/colour \
trunk/src/executor/representer/deserialiser/command_line \
trunk/src/executor/representer/deserialiser/character_reference \
trunk/src/executor/representer/deserialiser/authority \
trunk/src/executor/representer/deserialiser/ansi_escape_code \
trunk/src/executor/referencer \
trunk/src/executor/modifier/remover \
trunk/src/executor/modifier/overwriter \
trunk/src/executor/modifier/inserter \
trunk/src/executor/modifier/filler \
trunk/src/executor/modifier/emptier \
trunk/src/executor/modifier/copier \
trunk/src/executor/modifier/appender \
trunk/src/executor/memoriser \
trunk/src/executor/memoriser/reallocator \
trunk/src/executor/memoriser/deallocator \
trunk/src/executor/memoriser/creator \
trunk/src/executor/memoriser/allocator \
trunk/src/executor/manipulator \
trunk/src/executor/manipulator/integer \
trunk/src/executor/manipulator/character \
trunk/src/executor/maintainer \
trunk/src/executor/maintainer/starter/x_window_system \
trunk/src/executor/maintainer/starter/win32_display \
trunk/src/executor/maintainer/starter/win32_console \
trunk/src/executor/maintainer/starter/unix_terminal \
trunk/src/executor/maintainer/starter/terminal \
trunk/src/executor/maintainer/starter/socket \
trunk/src/executor/maintainer/starter/serial_port \
trunk/src/executor/maintainer/starter/opengl \
trunk/src/executor/maintainer/starter/display \
trunk/src/executor/maintainer/shutter/x_window_system \
trunk/src/executor/maintainer/shutter/win32_display \
trunk/src/executor/maintainer/shutter/win32_console \
trunk/src/executor/maintainer/shutter/unix_terminal \
trunk/src/executor/maintainer/shutter/terminal \
trunk/src/executor/maintainer/shutter/socket \
trunk/src/executor/maintainer/shutter/serial_port \
trunk/src/executor/maintainer/shutter/opengl \
trunk/src/executor/maintainer/shutter/display \
trunk/src/executor/logifier \
trunk/src/executor/logifier/integer \
trunk/src/executor/logifier/character \
trunk/src/executor/logifier/boolean \
trunk/src/executor/lifeguard \
trunk/src/executor/lifeguard/sensor/x_window_system \
trunk/src/executor/lifeguard/sensor/win32_display \
trunk/src/executor/lifeguard/sensor/win32_console \
trunk/src/executor/lifeguard/sensor/unix_terminal \
trunk/src/executor/lifeguard/sensor/terminal \
trunk/src/executor/lifeguard/sensor/socket \
trunk/src/executor/lifeguard/sensor/serial_port \
trunk/src/executor/lifeguard/sensor/display \
trunk/src/executor/lifeguard/interrupter \
trunk/src/executor/converter \
trunk/src/executor/converter/encoder/utf \
trunk/src/executor/converter/decoder/windows \
trunk/src/executor/converter/decoder/utf \
trunk/src/executor/converter/decoder/typecast \
trunk/src/executor/converter/decoder/iso_8859 \
trunk/src/executor/converter/decoder/ascii \
trunk/src/executor/comparator/suffix \
trunk/src/executor/comparator/subsequence \
trunk/src/executor/comparator/prefix \
trunk/src/executor/comparator \
trunk/src/executor/comparator/basic \
trunk/src/executor/comparator/basic/wide_character \
trunk/src/executor/comparator/basic/unsigned_long \
trunk/src/executor/comparator/basic/pointer \
trunk/src/executor/comparator/basic/integer \
trunk/src/executor/comparator/basic/fraction \
trunk/src/executor/comparator/basic/double \
trunk/src/executor/comparator/basic/complex \
trunk/src/executor/comparator/basic/character \
trunk/src/executor/comparator/all \
trunk/src/executor/communicator \
trunk/src/executor/communicator/sender/x_window_system \
trunk/src/executor/communicator/sender/win32_display \
trunk/src/executor/communicator/sender/unix_terminal \
trunk/src/executor/communicator/sender/terminal \
trunk/src/executor/communicator/sender/socket \
trunk/src/executor/communicator/sender/signal \
trunk/src/executor/communicator/sender/serial_port \
trunk/src/executor/communicator/sender/inline \
trunk/src/executor/communicator/sender/file \
trunk/src/executor/communicator/sender/display \
trunk/src/executor/communicator/receiver/x_window_system \
trunk/src/executor/communicator/receiver/win32_display \
trunk/src/executor/communicator/receiver/win32_console \
trunk/src/executor/communicator/receiver/unix_terminal \
trunk/src/executor/communicator/receiver/terminal \
trunk/src/executor/communicator/receiver/socket \
trunk/src/executor/communicator/receiver/serial_port \
trunk/src/executor/communicator/receiver/inline \
trunk/src/executor/communicator/receiver/file \
trunk/src/executor/communicator/receiver/display \
trunk/src/executor/commander/windows \
trunk/src/executor/commander/unix \
trunk/src/executor/commander/basic \
trunk/src/executor/caster/basic \
trunk/src/executor/caster/basic/integer \
trunk/src/executor/caster/basic/double \
trunk/src/executor/caster/basic/character \
trunk/src/executor/caster/all \
trunk/src/executor/calculator/basic \
trunk/src/executor/calculator/basic/pointer \
trunk/src/executor/calculator/basic/integer \
trunk/src/executor/calculator/basic/fraction \
trunk/src/executor/calculator/basic/double \
trunk/src/executor/calculator/basic/complex \
trunk/src/executor/calculator/basic/character \
trunk/src/executor/calculator/all \
trunk/src/executor/accessor/setter \
trunk/src/executor/accessor/name_getter \
trunk/src/executor/accessor/knowledge_getter \
trunk/src/executor/accessor/indicator \
trunk/src/executor/accessor/getter \
trunk/src/executor/accessor/counter \
trunk/src/controller \
trunk/src/controller/unglobaliser \
trunk/src/controller/optionaliser \
trunk/src/controller/manager \
trunk/src/controller/handler \
trunk/src/controller/globaliser \
trunk/src/controller/deoptionaliser \
trunk/src/controller/checker \
trunk/src/constant/type/cyboi \
trunk/src/constant/name/xml \
trunk/src/constant/name/xdt \
trunk/src/constant/name/uri \
trunk/src/constant/name/percent_encoding \
trunk/src/constant/name/http_request_uri \
trunk/src/constant/name/http \
trunk/src/constant/name/http/header \
trunk/src/constant/name/cybol \
trunk/src/constant/name/cybol/state/wui \
trunk/src/constant/name/cybol/state/tui \
trunk/src/constant/name/cybol/state \
trunk/src/constant/name/cybol/state/mouse \
trunk/src/constant/name/cybol/state/keyboard \
trunk/src/constant/name/cybol/state/gui \
trunk/src/constant/name/cybol/logic/run \
trunk/src/constant/name/cybol/logic/representation \
trunk/src/constant/name/cybol/logic/modification \
trunk/src/constant/name/cybol/logic/memory \
trunk/src/constant/name/cybol/logic/manipulation \
trunk/src/constant/name/cybol/logic/maintenance \
trunk/src/constant/name/cybol/logic/logic \
trunk/src/constant/name/cybol/logic/life \
trunk/src/constant/name/cybol/logic/flow \
trunk/src/constant/name/cybol/logic/comparison \
trunk/src/constant/name/cybol/logic/communication \
trunk/src/constant/name/cybol/logic/commander \
trunk/src/constant/name/cybol/logic/cast \
trunk/src/constant/name/cybol/logic/calculation \
trunk/src/constant/name/cybol/logic/access \
trunk/src/constant/name/cyboi/xdt \
trunk/src/constant/name/cyboi/uri \
trunk/src/constant/name/cyboi/state \
trunk/src/constant/name/cyboi/option \
trunk/src/constant/name/cyboi/knowledge \
trunk/src/constant/name/cyboi/http \
trunk/src/constant/name/cyboi/http/header \
trunk/src/constant/name/cyboi/authority \
trunk/src/constant/name/command_option/win32 \
trunk/src/constant/name/command_option/unix \
trunk/src/constant/name/character_reference \
trunk/src/constant/name/authority \
trunk/src/constant/model/xdt \
trunk/src/constant/model/uri \
trunk/src/constant/model/time_scale \
trunk/src/constant/model/text \
trunk/src/constant/model/terminal \
trunk/src/constant/model/service \
trunk/src/constant/model/language \
trunk/src/constant/model/http \
trunk/src/constant/model/html \
trunk/src/constant/model/cybol/state \
trunk/src/constant/model/cybol/socket \
trunk/src/constant/model/cybol/shape \
trunk/src/constant/model/cybol/logic \
trunk/src/constant/model/cybol/layout \
trunk/src/constant/model/cybol/http \
trunk/src/constant/model/cybol/colour \
trunk/src/constant/model/cybol/border \
trunk/src/constant/model/cyboi/test \
trunk/src/constant/model/cyboi/state \
trunk/src/constant/model/cyboi/state/colour \
trunk/src/constant/model/cyboi/option \
trunk/src/constant/model/cyboi/operation_mode \
trunk/src/constant/model/cyboi/log \
trunk/src/constant/model/cyboi/identification \
trunk/src/constant/model/command \
trunk/src/constant/model/character_entity_reference \
trunk/src/constant/model/character_code/windows \
trunk/src/constant/model/character_code/unicode \
trunk/src/constant/model/character_code/iso_8859 \
trunk/src/constant/model/character_code/iso_6429 \
trunk/src/constant/model/character_code/dos \
trunk/src/constant/model/character_code/ascii \
trunk/src/constant/model/ansi_escape_code \
trunk/src/constant/language/cybol/state \
trunk/src/constant/language/cyboi \
trunk/src/constant/format/cybol/state \
trunk/src/constant/format/cybol/logic \
trunk/src/constant/format/cyboi \
trunk/src/constant/encoding/cybol \
trunk/src/constant/encoding/cyboi \
trunk/src/constant/channel/cybol \
trunk/src/constant/channel/cyboi \
trunk/src/applicator/run \
trunk/src/applicator/represent \
trunk/src/applicator/modify \
trunk/src/applicator/memorise \
trunk/src/applicator/manipulate \
trunk/src/applicator/maintain \
trunk/src/applicator/logify \
trunk/src/applicator/live \
trunk/src/applicator/flow \
trunk/src/applicator/compare \
trunk/src/applicator/communicate \
trunk/src/applicator/command \
trunk/src/applicator/cast \
trunk/src/applicator/calculate \
trunk/src/applicator/access \
trunk/include/visualstudio/pthreadsw32/pthreads.2 \
trunk/include/visualstudio/pthreadsw32/pthreads.2/tests \
trunk/include/i586-mingw32msvc/include/X11/Xtrans \
trunk/doc/development/x11_and_xlib \
trunk/doc/development/ms_windows/example_3 \
trunk/doc/development/ms_windows/example_2 \
trunk/doc/development/ms_windows/example_1 \
trunk/doc/development/linux_console \
trunk/CYBOP/Debug/trunk/src/variable/type_size \
trunk/.metadata/.plugins/org.eclipse.cdt.make.core \

