/*
 * $RCSfile: numeric_character_reference_constants.c,v $
 *
 * Copyright (c) 1999-2007. Christian Heller and the CYBOP developers.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * http://www.cybop.net
 * - Cybernetics Oriented Programming -
 *
 * @version $Revision: 1.1 $ $Date: 2007-08-27 07:07:37 $ $Author: christian $
 * @author Christian Heller <christian.heller@tuxtax.de>
 */

#ifndef NUMERIC_CHARACTER_REFERENCE_CONSTANTS_SOURCE
#define NUMERIC_CHARACTER_REFERENCE_CONSTANTS_SOURCE

#include "../../../globals/constants/integer/integer_constants.c"

//
// The references &#00; to &#08; are unused.
//

/** The horizontal tab numeric character reference. */
static char HORIZONTAL_TAB_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '0', '9', ';'};
static char* HORIZONTAL_TAB_NUMERIC_CHARACTER_REFERENCE = HORIZONTAL_TAB_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* HORIZONTAL_TAB_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The line feed numeric character reference. */
static char LINE_FEED_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', ';'};
static char* LINE_FEED_NUMERIC_CHARACTER_REFERENCE = LINE_FEED_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LINE_FEED_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

//
// The references &#11; to &#12; are unused.
//

/** The carriage return numeric character reference. */
static char CARRIAGE_RETURN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '3', ';'};
static char* CARRIAGE_RETURN_NUMERIC_CHARACTER_REFERENCE = CARRIAGE_RETURN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CARRIAGE_RETURN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

//
// The references &#14; to &#31; are unused.
//

/** The space   numeric character reference. */
static char SPACE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '2', ';'};
static char* SPACE_NUMERIC_CHARACTER_REFERENCE = SPACE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SPACE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The exclamation mark ! numeric character reference. */
static char EXCLAMATION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '3', ';'};
static char* EXCLAMATION_MARK_NUMERIC_CHARACTER_REFERENCE = EXCLAMATION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* EXCLAMATION_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The quotation mark " numeric character reference. */
static char QUOTATION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '4', ';'};
static char* QUOTATION_MARK_NUMERIC_CHARACTER_REFERENCE = QUOTATION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* QUOTATION_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The number sign # numeric character reference. */
static char NUMBER_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '5', ';'};
static char* NUMBER_SIGN_NUMERIC_CHARACTER_REFERENCE = NUMBER_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* NUMBER_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The dollar sign $ numeric character reference. */
static char DOLLAR_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '6', ';'};
static char* DOLLAR_SIGN_NUMERIC_CHARACTER_REFERENCE = DOLLAR_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DOLLAR_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The percent sign % numeric character reference. */
static char PERCENT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '7', ';'};
static char* PERCENT_SIGN_NUMERIC_CHARACTER_REFERENCE = PERCENT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* PERCENT_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The ampersand & numeric character reference. */
static char AMPERSAND_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '8', ';'};
static char* AMPERSAND_NUMERIC_CHARACTER_REFERENCE = AMPERSAND_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* AMPERSAND_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The apostrophe ' numeric character reference. */
static char APOSTROPHE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '3', '9', ';'};
static char* APOSTROPHE_NUMERIC_CHARACTER_REFERENCE = APOSTROPHE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* APOSTROPHE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The left parenthesis ( numeric character reference. */
static char LEFT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '0', ';'};
static char* LEFT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE = LEFT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LEFT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The right parenthesis ) numeric character reference. */
static char RIGHT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '1', ';'};
static char* RIGHT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE = RIGHT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* RIGHT_PARENTHESIS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The asterisk * numeric character reference. */
static char ASTERISK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '2', ';'};
static char* ASTERISK_NUMERIC_CHARACTER_REFERENCE = ASTERISK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* ASTERISK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The plus sign + numeric character reference. */
static char PLUS_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '3', ';'};
static char* PLUS_SIGN_NUMERIC_CHARACTER_REFERENCE = PLUS_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* PLUS_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The comma , numeric character reference. */
static char COMMA_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '4', ';'};
static char* COMMA_NUMERIC_CHARACTER_REFERENCE = COMMA_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* COMMA_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The hyphen - numeric character reference. */
static char HYPHEN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '5', ';'};
static char* HYPHEN_NUMERIC_CHARACTER_REFERENCE = HYPHEN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* HYPHEN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The period (fullstop, dot) . numeric character reference. */
static char PERIOD_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '6', ';'};
static char* PERIOD_NUMERIC_CHARACTER_REFERENCE = PERIOD_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* PERIOD_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The solidus (slash) / numeric character reference. */
static char SOLIDUS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '7', ';'};
static char* SOLIDUS_NUMERIC_CHARACTER_REFERENCE = SOLIDUS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SOLIDUS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 0 numeric character reference. */
static char DIGIT_0_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '8', ';'};
static char* DIGIT_0_NUMERIC_CHARACTER_REFERENCE = DIGIT_0_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_0_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 1 numeric character reference. */
static char DIGIT_1_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '4', '9', ';'};
static char* DIGIT_1_NUMERIC_CHARACTER_REFERENCE = DIGIT_1_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_1_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 2 numeric character reference. */
static char DIGIT_2_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '0', ';'};
static char* DIGIT_2_NUMERIC_CHARACTER_REFERENCE = DIGIT_2_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_2_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 3 numeric character reference. */
static char DIGIT_3_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '1', ';'};
static char* DIGIT_3_NUMERIC_CHARACTER_REFERENCE = DIGIT_3_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_3_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 4 numeric character reference. */
static char DIGIT_4_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '2', ';'};
static char* DIGIT_4_NUMERIC_CHARACTER_REFERENCE = DIGIT_4_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_4_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 5 numeric character reference. */
static char DIGIT_5_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '3', ';'};
static char* DIGIT_5_NUMERIC_CHARACTER_REFERENCE = DIGIT_5_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_5_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 6 numeric character reference. */
static char DIGIT_6_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '4', ';'};
static char* DIGIT_6_NUMERIC_CHARACTER_REFERENCE = DIGIT_6_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_6_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 7 numeric character reference. */
static char DIGIT_7_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '5', ';'};
static char* DIGIT_7_NUMERIC_CHARACTER_REFERENCE = DIGIT_7_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_7_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 8 numeric character reference. */
static char DIGIT_8_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '6', ';'};
static char* DIGIT_8_NUMERIC_CHARACTER_REFERENCE = DIGIT_8_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_8_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The digit 9 numeric character reference. */
static char DIGIT_9_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '7', ';'};
static char* DIGIT_9_NUMERIC_CHARACTER_REFERENCE = DIGIT_9_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIGIT_9_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The colon : numeric character reference. */
static char COLON_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '8', ';'};
static char* COLON_NUMERIC_CHARACTER_REFERENCE = COLON_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* COLON_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The semi-colon ; numeric character reference. */
static char SEMICOLON_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '5', '9', ';'};
static char* SEMICOLON_NUMERIC_CHARACTER_REFERENCE = SEMICOLON_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SEMICOLON_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The less than < numeric character reference. */
static char LESS_THAN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '0', ';'};
static char* LESS_THAN_NUMERIC_CHARACTER_REFERENCE = LESS_THAN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LESS_THAN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The equals sign = numeric character reference. */
static char EQUALS_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '1', ';'};
static char* EQUALS_SIGN_NUMERIC_CHARACTER_REFERENCE = EQUALS_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* EQUALS_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The greater than > numeric character reference. */
static char GREATER_THAN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '2', ';'};
static char* GREATER_THAN_NUMERIC_CHARACTER_REFERENCE = GREATER_THAN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* GREATER_THAN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The question mark ? numeric character reference. */
static char QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '3', ';'};
static char* QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE = QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The commercial at @ numeric character reference. */
static char COMMERCIAL_AT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '4', ';'};
static char* COMMERCIAL_AT_NUMERIC_CHARACTER_REFERENCE = COMMERCIAL_AT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* COMMERCIAL_AT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter a numeric character reference. */
static char CAPITAL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '5', ';'};
static char* CAPITAL_LETTER_A_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter b numeric character reference. */
static char CAPITAL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '6', ';'};
static char* CAPITAL_LETTER_B_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter c numeric character reference. */
static char CAPITAL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '7', ';'};
static char* CAPITAL_LETTER_C_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter d numeric character reference. */
static char CAPITAL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '8', ';'};
static char* CAPITAL_LETTER_D_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter e numeric character reference. */
static char CAPITAL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '6', '9', ';'};
static char* CAPITAL_LETTER_E_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter f numeric character reference. */
static char CAPITAL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '0', ';'};
static char* CAPITAL_LETTER_F_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter g numeric character reference. */
static char CAPITAL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '1', ';'};
static char* CAPITAL_LETTER_G_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter h numeric character reference. */
static char CAPITAL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '2', ';'};
static char* CAPITAL_LETTER_H_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter i numeric character reference. */
static char CAPITAL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '3', ';'};
static char* CAPITAL_LETTER_I_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter j numeric character reference. */
static char CAPITAL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '4', ';'};
static char* CAPITAL_LETTER_J_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter k numeric character reference. */
static char CAPITAL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '5', ';'};
static char* CAPITAL_LETTER_K_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter l numeric character reference. */
static char CAPITAL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '6', ';'};
static char* CAPITAL_LETTER_L_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter m numeric character reference. */
static char CAPITAL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '7', ';'};
static char* CAPITAL_LETTER_M_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter n numeric character reference. */
static char CAPITAL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '8', ';'};
static char* CAPITAL_LETTER_N_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter o numeric character reference. */
static char CAPITAL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '7', '9', ';'};
static char* CAPITAL_LETTER_O_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter p numeric character reference. */
static char CAPITAL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '0', ';'};
static char* CAPITAL_LETTER_P_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter q numeric character reference. */
static char CAPITAL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '1', ';'};
static char* CAPITAL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter r numeric character reference. */
static char CAPITAL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '2', ';'};
static char* CAPITAL_LETTER_R_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter s numeric character reference. */
static char CAPITAL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '3', ';'};
static char* CAPITAL_LETTER_S_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter t numeric character reference. */
static char CAPITAL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '4', ';'};
static char* CAPITAL_LETTER_T_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter u numeric character reference. */
static char CAPITAL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '5', ';'};
static char* CAPITAL_LETTER_U_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter v numeric character reference. */
static char CAPITAL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '6', ';'};
static char* CAPITAL_LETTER_V_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter w numeric character reference. */
static char CAPITAL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '7', ';'};
static char* CAPITAL_LETTER_W_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter x numeric character reference. */
static char CAPITAL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '8', ';'};
static char* CAPITAL_LETTER_X_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter y numeric character reference. */
static char CAPITAL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '8', '9', ';'};
static char* CAPITAL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The capital letter z numeric character reference. */
static char CAPITAL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '0', ';'};
static char* CAPITAL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE = CAPITAL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The left square bracket [ numeric character reference. */
static char LEFT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '1', ';'};
static char* LEFT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE = LEFT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LEFT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The reverse solidus (backslash) \ numeric character reference. */
static char REVERSE_SOLIDUS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '2', ';'};
static char* REVERSE_SOLIDUS_NUMERIC_CHARACTER_REFERENCE = REVERSE_SOLIDUS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* REVERSE_SOLIDUS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The right square bracket ] numeric character reference. */
static char RIGHT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '3', ';'};
static char* RIGHT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE = RIGHT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* RIGHT_SQUARE_BRACKET_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The caret ^ numeric character reference. */
static char CARET_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '4', ';'};
static char* CARET_NUMERIC_CHARACTER_REFERENCE = CARET_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CARET_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The horizontal bar (underscore) _ numeric character reference. */
static char HORIZONTAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '5', ';'};
static char* HORIZONTAL_BAR_NUMERIC_CHARACTER_REFERENCE = HORIZONTAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* HORIZONTAL_BAR_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The grave accent ` numeric character reference. */
static char GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '6', ';'};
static char* GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The small letter a numeric character reference. */
static char SMALL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '7', ';'};
static char* SMALL_LETTER_A_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_A_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The small letter b numeric character reference. */
static char SMALL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '8', ';'};
static char* SMALL_LETTER_B_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_B_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The small letter c numeric character reference. */
static char SMALL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '9', '9', ';'};
static char* SMALL_LETTER_C_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_C_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_5_INTEGER_ARRAY;

/** The small letter d numeric character reference. */
static char SMALL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '0', ';'};
static char* SMALL_LETTER_D_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_D_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter e numeric character reference. */
static char SMALL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '1', ';'};
static char* SMALL_LETTER_E_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_E_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter f numeric character reference. */
static char SMALL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '2', ';'};
static char* SMALL_LETTER_F_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_F_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter g numeric character reference. */
static char SMALL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '3', ';'};
static char* SMALL_LETTER_G_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_G_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter h numeric character reference. */
static char SMALL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '4', ';'};
static char* SMALL_LETTER_H_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_H_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter i numeric character reference. */
static char SMALL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '5', ';'};
static char* SMALL_LETTER_I_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_I_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter j numeric character reference. */
static char SMALL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '6', ';'};
static char* SMALL_LETTER_J_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_J_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter k numeric character reference. */
static char SMALL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '7', ';'};
static char* SMALL_LETTER_K_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_K_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter l numeric character reference. */
static char SMALL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '8', ';'};
static char* SMALL_LETTER_L_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_L_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter m numeric character reference. */
static char SMALL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '0', '9', ';'};
static char* SMALL_LETTER_M_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_M_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter n numeric character reference. */
static char SMALL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '0', ';'};
static char* SMALL_LETTER_N_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_N_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter o numeric character reference. */
static char SMALL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '1', ';'};
static char* SMALL_LETTER_O_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_O_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter p numeric character reference. */
static char SMALL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '2', ';'};
static char* SMALL_LETTER_P_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_P_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter q numeric character reference. */
static char SMALL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '3', ';'};
static char* SMALL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_Q_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter r numeric character reference. */
static char SMALL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '4', ';'};
static char* SMALL_LETTER_R_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_R_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter s numeric character reference. */
static char SMALL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '5', ';'};
static char* SMALL_LETTER_S_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_S_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter t numeric character reference. */
static char SMALL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '6', ';'};
static char* SMALL_LETTER_T_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_T_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter u numeric character reference. */
static char SMALL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '7', ';'};
static char* SMALL_LETTER_U_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_U_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter v numeric character reference. */
static char SMALL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '8', ';'};
static char* SMALL_LETTER_V_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_V_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter w numeric character reference. */
static char SMALL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '1', '9', ';'};
static char* SMALL_LETTER_W_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_W_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter x numeric character reference. */
static char SMALL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '0', ';'};
static char* SMALL_LETTER_X_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_X_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter y numeric character reference. */
static char SMALL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '1', ';'};
static char* SMALL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_Y_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small letter z numeric character reference. */
static char SMALL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '2', ';'};
static char* SMALL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE = SMALL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_LETTER_Z_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The left curly brace { numeric character reference. */
static char LEFT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '3', ';'};
static char* LEFT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE = LEFT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LEFT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The vertical bar | numeric character reference. */
static char VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '4', ';'};
static char* VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE = VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The right curly brace } numeric character reference. */
static char RIGHT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '5', ';'};
static char* RIGHT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE = RIGHT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* RIGHT_CURLY_BRACE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The tilde ~ numeric character reference. */
static char TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '2', '6', ';'};
static char* TILDE_NUMERIC_CHARACTER_REFERENCE = TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

//
// The references &#127; to &#159; are unused.
//

/** The non-breaking space   numeric character reference. */
static char NON_BREAKING_SPACE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '0', ';'};
static char* NON_BREAKING_SPACE_NUMERIC_CHARACTER_REFERENCE = NON_BREAKING_SPACE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* NON_BREAKING_SPACE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The inverted exclamation numeric character reference. */
static char INVERTED_EXCLAMATION_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '1', ';'};
static char* INVERTED_EXCLAMATION_NUMERIC_CHARACTER_REFERENCE = INVERTED_EXCLAMATION_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* INVERTED_EXCLAMATION_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The cent sign numeric character reference. */
static char CENT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '2', ';'};
static char* CENT_SIGN_NUMERIC_CHARACTER_REFERENCE = CENT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CENT_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The pound sterling numeric character reference. */
static char POUND_STERLING_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '3', ';'};
static char* POUND_STERLING_NUMERIC_CHARACTER_REFERENCE = POUND_STERLING_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* POUND_STERLING_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The general currency sign numeric character reference. */
static char GENERAL_CURRENCY_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '4', ';'};
static char* GENERAL_CURRENCY_NUMERIC_CHARACTER_REFERENCE = GENERAL_CURRENCY_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* GENERAL_CURRENCY_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The yen sign numeric character reference. */
static char YEN_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '5', ';'};
static char* YEN_SIGN_NUMERIC_CHARACTER_REFERENCE = YEN_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* YEN_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The broken vertical bar numeric character reference. */
static char BROKEN_VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '6', ';'};
static char* BROKEN_VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE = BROKEN_VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* BROKEN_VERTICAL_BAR_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The section sign numeric character reference. */
static char SECTION_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '7', ';'};
static char* SECTION_SIGN_NUMERIC_CHARACTER_REFERENCE = SECTION_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SECTION_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The umlaut (dieresis) numeric character reference. */
static char UMLAUT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '8', ';'};
static char* UMLAUT_NUMERIC_CHARACTER_REFERENCE = UMLAUT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* UMLAUT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The copyright numeric character reference. */
static char COPYRIGHT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '6', '9', ';'};
static char* COPYRIGHT_NUMERIC_CHARACTER_REFERENCE = COPYRIGHT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* COPYRIGHT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The feminine ordinal numeric character reference. */
static char FEMININE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '0', ';'};
static char* FEMININE_ORDINAL_NUMERIC_CHARACTER_REFERENCE = FEMININE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* FEMININE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The left angle quote, guillemotleft numeric character reference. */
static char LEFT_ANGLE_QUOTE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '1', ';'};
static char* LEFT_ANGLE_QUOTE_NUMERIC_CHARACTER_REFERENCE = LEFT_ANGLE_QUOTE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* LEFT_ANGLE_QUOTE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The not sign numeric character reference. */
static char NOT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '2', ';'};
static char* NOT_SIGN_NUMERIC_CHARACTER_REFERENCE = NOT_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* NOT_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The soft hyphen numeric character reference. */
static char SOFT_HYPHEN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '3', ';'};
static char* SOFT_HYPHEN_NUMERIC_CHARACTER_REFERENCE = SOFT_HYPHEN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SOFT_HYPHEN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The registered trademark numeric character reference. */
static char REGISTERED_TRADEMARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '4', ';'};
static char* REGISTERED_TRADEMARK_NUMERIC_CHARACTER_REFERENCE = REGISTERED_TRADEMARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* REGISTERED_TRADEMARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The macron accent numeric character reference. */
static char MACRON_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '5', ';'};
static char* MACRON_ACCENT_NUMERIC_CHARACTER_REFERENCE = MACRON_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* MACRON_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The degree sign numeric character reference. */
static char DEGREE_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '6', ';'};
static char* DEGREE_SIGN_NUMERIC_CHARACTER_REFERENCE = DEGREE_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DEGREE_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The plus or minus numeric character reference. */
static char PLUS_OR_MINUS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '7', ';'};
static char* PLUS_OR_MINUS_NUMERIC_CHARACTER_REFERENCE = PLUS_OR_MINUS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* PLUS_OR_MINUS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The superscript two ² numeric character reference. */
static char SUPERSCRIPT_TWO_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '8', ';'};
static char* SUPERSCRIPT_TWO_NUMERIC_CHARACTER_REFERENCE = SUPERSCRIPT_TWO_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SUPERSCRIPT_TWO_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The superscript three ³ numeric character reference. */
static char SUPERSCRIPT_THREE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '7', '9', ';'};
static char* SUPERSCRIPT_THREE_NUMERIC_CHARACTER_REFERENCE = SUPERSCRIPT_THREE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SUPERSCRIPT_THREE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The acute accent numeric character reference. */
static char ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '0', ';'};
static char* ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The micro sign numeric character reference. */
static char MICRO_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '1', ';'};
static char* MICRO_SIGN_NUMERIC_CHARACTER_REFERENCE = MICRO_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* MICRO_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The paragraph sign § numeric character reference. */
static char PARAGRAPH_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '2', ';'};
static char* PARAGRAPH_SIGN_NUMERIC_CHARACTER_REFERENCE = PARAGRAPH_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* PARAGRAPH_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The middle dot numeric character reference. */
static char MIDDLE_DOT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '3', ';'};
static char* MIDDLE_DOT_NUMERIC_CHARACTER_REFERENCE = MIDDLE_DOT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* MIDDLE_DOT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The cedilla numeric character reference. */
static char CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '4', ';'};
static char* CEDILLA_NUMERIC_CHARACTER_REFERENCE = CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CEDILLA_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The superscript one ¹ numeric character reference. */
static char SUPERSCRIPT_ONE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '5', ';'};
static char* SUPERSCRIPT_ONE_NUMERIC_CHARACTER_REFERENCE = SUPERSCRIPT_ONE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SUPERSCRIPT_ONE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The masculine ordinal numeric character reference. */
static char MASCULINE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '6', ';'};
static char* MASCULINE_ORDINAL_NUMERIC_CHARACTER_REFERENCE = MASCULINE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* MASCULINE_ORDINAL_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The right angle quote guillemotright numeric character reference. */
static char RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '7', ';'};
static char* RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_CHARACTER_REFERENCE = RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The fraction one-fourth numeric character reference. */
static char FRACTION_ONE_FOURTH_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '8', ';'};
static char* FRACTION_ONE_FOURTH_NUMERIC_CHARACTER_REFERENCE = FRACTION_ONE_FOURTH_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* FRACTION_ONE_FOURTH_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The fraction one-half ½ numeric character reference. */
static char FRACTION_ONE_HALF_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '8', '9', ';'};
static char* FRACTION_ONE_HALF_NUMERIC_CHARACTER_REFERENCE = FRACTION_ONE_HALF_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* FRACTION_ONE_HALF_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The fraction three-fourths ¼ numeric character reference. */
static char FRACTION_THREE_FOURTHS_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '0', ';'};
static char* FRACTION_THREE_FOURTHS_NUMERIC_CHARACTER_REFERENCE = FRACTION_THREE_FOURTHS_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* FRACTION_THREE_FOURTHS_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The inverted question mark numeric character reference. */
static char INVERTED_QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '1', ';'};
static char* INVERTED_QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE = INVERTED_QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* INVERTED_QUESTION_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a grave accent numeric character reference. */
static char CAPITAL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '2', ';'};
static char* CAPITAL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a acute accent numeric character reference. */
static char CAPITAL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '3', ';'};
static char* CAPITAL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a circumflex accent numeric character reference. */
static char CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '4', ';'};
static char* CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a tilde numeric character reference. */
static char CAPITAL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '5', ';'};
static char* CAPITAL_A_TILDE_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a umlaut mark (dieresis) numeric character reference. */
static char CAPITAL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '6', ';'};
static char* CAPITAL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital a ring numeric character reference. */
static char CAPITAL_A_RING_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '7', ';'};
static char* CAPITAL_A_RING_NUMERIC_CHARACTER_REFERENCE = CAPITAL_A_RING_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_A_RING_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital ae dipthong (ligature) numeric character reference. */
static char CAPITAL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '8', ';'};
static char* CAPITAL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE = CAPITAL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital c cedilla numeric character reference. */
static char CAPITAL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '1', '9', '9', ';'};
static char* CAPITAL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE = CAPITAL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital e grave accent numeric character reference. */
static char CAPITAL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '0', ';'};
static char* CAPITAL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital e acute accent numeric character reference. */
static char CAPITAL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '1', ';'};
static char* CAPITAL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital e circumflex accent numeric character reference. */
static char CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '2', ';'};
static char* CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital e umlaut mark (dieresis) numeric character reference. */
static char CAPITAL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '3', ';'};
static char* CAPITAL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = CAPITAL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital i grave accent numeric character reference. */
static char CAPITAL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '4', ';'};
static char* CAPITAL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital i acute accent numeric character reference. */
static char CAPITAL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '5', ';'};
static char* CAPITAL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital i circumflex accent numeric character reference. */
static char CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '6', ';'};
static char* CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital i umlaut mark (dieresis) numeric character reference. */
static char CAPITAL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '7', ';'};
static char* CAPITAL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = CAPITAL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital eth icelandic numeric character reference. */
static char CAPITAL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '8', ';'};
static char* CAPITAL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE = CAPITAL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital n tilde numeric character reference. */
static char CAPITAL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '0', '9', ';'};
static char* CAPITAL_N_TILDE_NUMERIC_CHARACTER_REFERENCE = CAPITAL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o grave accent numeric character reference. */
static char CAPITAL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '0', ';'};
static char* CAPITAL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o acute accent numeric character reference. */
static char CAPITAL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '1', ';'};
static char* CAPITAL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o circumflex accent numeric character reference. */
static char CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '2', ';'};
static char* CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o tilde numeric character reference. */
static char CAPITAL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '3', ';'};
static char* CAPITAL_O_TILDE_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o umlaut mark (dieresis) numeric character reference. */
static char CAPITAL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '4', ';'};
static char* CAPITAL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The multiply sign numeric character reference. */
static char MULTIPLY_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '5', ';'};
static char* MULTIPLY_SIGN_NUMERIC_CHARACTER_REFERENCE = MULTIPLY_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* MULTIPLY_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital o slash numeric character reference. */
static char CAPITAL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '6', ';'};
static char* CAPITAL_O_SLASH_NUMERIC_CHARACTER_REFERENCE = CAPITAL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital u grave accent numeric character reference. */
static char CAPITAL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '7', ';'};
static char* CAPITAL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital u acute accent numeric character reference. */
static char CAPITAL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '8', ';'};
static char* CAPITAL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital u circumflex accent numeric character reference. */
static char CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '1', '9', ';'};
static char* CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital u umlaut mark (dieresis) numeric character reference. */
static char CAPITAL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '0', ';'};
static char* CAPITAL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = CAPITAL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital y acute accent numeric character reference. */
static char CAPITAL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '1', ';'};
static char* CAPITAL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = CAPITAL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The capital thorn icelandic numeric character reference. */
static char CAPITAL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '2', ';'};
static char* CAPITAL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE = CAPITAL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* CAPITAL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small sharp s german (sz ligature) numeric character reference. */
static char SMALL_SHARP_S_GERMAN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '3', ';'};
static char* SMALL_SHARP_S_GERMAN_NUMERIC_CHARACTER_REFERENCE = SMALL_SHARP_S_GERMAN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_SHARP_S_GERMAN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a grave accent numeric character reference. */
static char SMALL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '4', ';'};
static char* SMALL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a acute accent numeric character reference. */
static char SMALL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '5', ';'};
static char* SMALL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a circumflex accent numeric character reference. */
static char SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '6', ';'};
static char* SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a tilde numeric character reference. */
static char SMALL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '7', ';'};
static char* SMALL_A_TILDE_NUMERIC_CHARACTER_REFERENCE = SMALL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a umlaut mark (dieresis) numeric character reference. */
static char SMALL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '8', ';'};
static char* SMALL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small a ring numeric character reference. */
static char SMALL_A_RING_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '2', '9', ';'};
static char* SMALL_A_RING_NUMERIC_CHARACTER_REFERENCE = SMALL_A_RING_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_A_RING_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small ae dipthong (ligature) numeric character reference. */
static char SMALL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '0', ';'};
static char* SMALL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE = SMALL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_AE_DIPTHONG_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small c cedilla numeric character reference. */
static char SMALL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '1', ';'};
static char* SMALL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE = SMALL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_C_CEDILLA_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small e grave accent numeric character reference. */
static char SMALL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '2', ';'};
static char* SMALL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_E_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small e acute accent numeric character reference. */
static char SMALL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '3', ';'};
static char* SMALL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_E_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small e circumflex accent numeric character reference. */
static char SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '4', ';'};
static char* SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small e umlaut mark (dieresis) numeric character reference. */
static char SMALL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '5', ';'};
static char* SMALL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_E_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small i grave accent numeric character reference. */
static char SMALL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '6', ';'};
static char* SMALL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_I_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small i acute accent numeric character reference. */
static char SMALL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '7', ';'};
static char* SMALL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_I_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small i circumflex accent numeric character reference. */
static char SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '8', ';'};
static char* SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small i umlaut mark (dieresis) numeric character reference. */
static char SMALL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '3', '9', ';'};
static char* SMALL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_I_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small eth icelandic numeric character reference. */
static char SMALL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '0', ';'};
static char* SMALL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE = SMALL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_ETH_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small n tilde numeric character reference. */
static char SMALL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '1', ';'};
static char* SMALL_N_TILDE_NUMERIC_CHARACTER_REFERENCE = SMALL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_N_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o grave accent numeric character reference. */
static char SMALL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '2', ';'};
static char* SMALL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o acute accent numeric character reference. */
static char SMALL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '3', ';'};
static char* SMALL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o circumflex accent numeric character reference. */
static char SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '4', ';'};
static char* SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o tilde numeric character reference. */
static char SMALL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '5', ';'};
static char* SMALL_O_TILDE_NUMERIC_CHARACTER_REFERENCE = SMALL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_TILDE_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o umlaut mark (dieresis) numeric character reference. */
static char SMALL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '6', ';'};
static char* SMALL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The division sign numeric character reference. */
static char DIVISION_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '7', ';'};
static char* DIVISION_SIGN_NUMERIC_CHARACTER_REFERENCE = DIVISION_SIGN_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* DIVISION_SIGN_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small o slash numeric character reference. */
static char SMALL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '8', ';'};
static char* SMALL_O_SLASH_NUMERIC_CHARACTER_REFERENCE = SMALL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_O_SLASH_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small u grave accent numeric character reference. */
static char SMALL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '4', '9', ';'};
static char* SMALL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_U_GRAVE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small u acute accent numeric character reference. */
static char SMALL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '0', ';'};
static char* SMALL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_U_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small u circumflex accent numeric character reference. */
static char SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '1', ';'};
static char* SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small u umlaut mark (dieresis) numeric character reference. */
static char SMALL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '2', ';'};
static char* SMALL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_U_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small y acute accent numeric character reference. */
static char SMALL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '3', ';'};
static char* SMALL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE = SMALL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_Y_ACUTE_ACCENT_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small thorn icelandic numeric character reference. */
static char SMALL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '4', ';'};
static char* SMALL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE = SMALL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_THORN_ICELANDIC_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/** The small y umlaut mark (dieresis) numeric character reference. */
static char SMALL_Y_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY[] = {'&', '#', '2', '5', '5', ';'};
static char* SMALL_Y_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE = SMALL_Y_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_ARRAY;
static int* SMALL_Y_UMLAUT_MARK_NUMERIC_CHARACTER_REFERENCE_COUNT = NUMBER_6_INTEGER_ARRAY;

/* NUMERIC_CHARACTER_REFERENCE_CONSTANTS_SOURCE */
#endif
