/*
 * Copyright (C) 1999-2011. Christian Heller.
 *
 * This file is part of the Cybernetics Oriented Interpreter (CYBOI).
 *
 * CYBOI is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * CYBOI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CYBOI.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org>
 * Christian Heller <christian.heller@tuxtax.de>
 *
 * @version $RCSfile: character_entity_xml_model.c,v $ $Revision: 1.4 $ $Date: 2009-01-31 16:06:30 $ $Author: christian $
 * @author Christian Heller <christian.heller@tuxtax.de>
 */

#ifndef CHARACTER_ENTITY_XML_MODEL_SOURCE
#define CHARACTER_ENTITY_XML_MODEL_SOURCE

#include <stddef.h>
#include "../../../constant/model/memory/integer_memory_model.c"

/** The quotation mark character entity xml model. */
static wchar_t QUOTATION_MARK_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'q', L'u', L'o', L't'};
static wchar_t* QUOTATION_MARK_CHARACTER_ENTITY_XML_MODEL = QUOTATION_MARK_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* QUOTATION_MARK_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The ampersand character entity xml model. */
static wchar_t AMPERSAND_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'a', L'm', L'p'};
static wchar_t* AMPERSAND_CHARACTER_ENTITY_XML_MODEL = AMPERSAND_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* AMPERSAND_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The apostrophe character entity xml model. CAUTION! It is only used in XHTML. */
static wchar_t APOSTROPHE_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'a', L'p', L'o', L's'};
static wchar_t* APOSTROPHE_CHARACTER_ENTITY_XML_MODEL = APOSTROPHE_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* APOSTROPHE_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The less than sign character entity xml model. */
static wchar_t LESS_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'l', L't'};
static wchar_t* LESS_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL = LESS_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* LESS_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_2_INTEGER_MEMORY_MODEL_ARRAY;

/** The greater than sign character entity xml model. */
static wchar_t GREATER_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'g', L't'};
static wchar_t* GREATER_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL = GREATER_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* GREATER_THAN_SIGN_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_2_INTEGER_MEMORY_MODEL_ARRAY;

/* Begin Thiele, Thomas and Simon, Friedemann */
/* Greek Letters */

/** The	small alpha character entity xml model. */
static wchar_t SMALL_ALPHA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'a', L'g', L'r'};
static wchar_t* SMALL_ALPHA_CHARACTER_ENTITY_XML_MODEL = SMALL_ALPHA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_ALPHA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Alpha character entity xml model. */
static wchar_t CAPITAL_ALPHA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'A', L'g', L'r'};
static wchar_t* CAPITAL_ALPHA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_ALPHA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_ALPHA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small beta character entity xml model. */
static wchar_t SMALL_BETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'b', L'g', L'r'};
static wchar_t* SMALL_BETA_CHARACTER_ENTITY_XML_MODEL = SMALL_BETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_BETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capial Beta character entity xml model. */
static wchar_t CAPITAL_BETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'B', L'g', L'r'};
static wchar_t* CAPITAL_BETA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_BETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_BETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small gamma character entity xml model. */
static wchar_t SMALL_GAMMA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'g', L'g', L'r'};
static wchar_t* SMALL_GAMMA_CHARACTER_ENTITY_XML_MODEL = SMALL_GAMMA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_GAMMA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Gamma character entity xml model. */
static wchar_t CAPITAL_GAMMA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'G', L'g', L'r'};
static wchar_t* CAPITAL_GAMMA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_GAMMA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_GAMMA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small delta character entity xml model. */
static wchar_t SMALL_DELTA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'd', L'g', L'r'};
static wchar_t* SMALL_DELTA_CHARACTER_ENTITY_XML_MODEL = SMALL_DELTA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_DELTA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Delta character entity xml model. */
static wchar_t CAPITAL_DELTA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'D', L'g', L'r'};
static wchar_t* CAPITAL_DELTA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_DELTA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_DELTA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small epsilon character entity xml model. */
static wchar_t SMALL_EPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'e', L'g', L'r'};
static wchar_t* SMALL_EPSILON_CHARACTER_ENTITY_XML_MODEL = SMALL_EPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_EPSILON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Epsilon character entity xml model. */
static wchar_t CAPITAL_EPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'E', L'g', L'r'};
static wchar_t* CAPITAL_EPSILON_CHARACTER_ENTITY_XML_MODEL = CAPITAL_EPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_EPSILON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small zeta character entity xml model. */
static wchar_t SMALL_ZETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'z', L'g', L'r'};
static wchar_t* SMALL_ZETA_CHARACTER_ENTITY_XML_MODEL = SMALL_ZETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_ZETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Zeta character entity xml model. */
static wchar_t CAPITAL_ZETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'Z', L'g', L'r'};
static wchar_t* CAPITAL_ZETA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_ZETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_ZETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small eta character entity xml model. */
static wchar_t SMALL_ETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'e', L'e', L'g', L'r'};
static wchar_t* SMALL_ETA_CHARACTER_ENTITY_XML_MODEL = SMALL_ETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_ETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Eta character entity xml model. */
static wchar_t CAPITAL_ETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'E', L'e', L'g', L'r'};
static wchar_t* CAPITAL_ETA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_ETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_ETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small theta character entity xml model. */
static wchar_t SMALL_THETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L't', L'h', L'g', L'r'};
static wchar_t* SMALL_THETA_CHARACTER_ENTITY_XML_MODEL = SMALL_THETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_THETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Theta character entity xml model. */
static wchar_t CAPITAL_THETA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'T', L'h', L'g', L'r'};
static wchar_t* CAPITAL_THETA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_THETA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_THETA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small iota character entity xml model. */
static wchar_t SMALL_IOTA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'i', L'g', L'r'};
static wchar_t* SMALL_IOTA_CHARACTER_ENTITY_XML_MODEL = SMALL_IOTA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_IOTA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Iota character entity xml model. */
static wchar_t CAPITAL_IOTA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'I', L'g', L'r'};
static wchar_t* CAPITAL_IOTA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_IOTA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_IOTA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small kappa character entity xml model. */
static wchar_t SMALL_KAPPA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'k', L'g', L'r'};
static wchar_t* SMALL_KAPPA_CHARACTER_ENTITY_XML_MODEL = SMALL_KAPPA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_KAPPA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Kappa character entity xml model. */
static wchar_t CAPITAL_KAPPA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'K', L'g', L'r'};
static wchar_t* CAPITAL_KAPPA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_KAPPA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_KAPPA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small lambda character entity xml model. */
static wchar_t SMALL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'l', L'g', L'r'};
static wchar_t* SMALL_LAMBDA_CHARACTER_ENTITY_XML_MODEL = SMALL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Lambda character entity xml model. */
static wchar_t CAPITAL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'L', L'g', L'r'};
static wchar_t* CAPITAL_LAMBDA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_LAMBDA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small mu character entity xml model. */
static wchar_t SMALL_MU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'm', L'g', L'r'};
static wchar_t* SMALL_MU_CHARACTER_ENTITY_XML_MODEL = SMALL_MU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_MU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Mu character entity xml model. */
static wchar_t CAPITAL_MU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'M', L'g', L'r'};
static wchar_t* CAPITAL_MU_CHARACTER_ENTITY_XML_MODEL = CAPITAL_MU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_MU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small nu character entity xml model. */
static wchar_t SMALL_NU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'n', L'g', L'r'};
static wchar_t* SMALL_NU_CHARACTER_ENTITY_XML_MODEL = SMALL_NU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_NU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Nu character entity xml model. */
static wchar_t CAPITAL_NU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'N', L'g', L'r'};
static wchar_t* CAPITAL_NU_CHARACTER_ENTITY_XML_MODEL = CAPITAL_NU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_NU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small xi character entity xml model. */
static wchar_t SMALL_XI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'x', L'g', L'r'};
static wchar_t* SMALL_XI_CHARACTER_ENTITY_XML_MODEL = SMALL_XI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_XI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Xi character entity xml model. */
static wchar_t CAPITAL_XI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'X', L'g', L'r'};
static wchar_t* CAPITAL_XI_CHARACTER_ENTITY_XML_MODEL = CAPITAL_XI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_XI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small omicron character entity xml model. */
static wchar_t SMALL_OMICRON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'o', L'g', L'r'};
static wchar_t* SMALL_OMICRON_CHARACTER_ENTITY_XML_MODEL = SMALL_OMICRON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_OMICRON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Omicron character entity xml model. */
static wchar_t CAPITAL_OMICRON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'O', L'g', L'r'};
static wchar_t* CAPITAL_OMICRON_CHARACTER_ENTITY_XML_MODEL = CAPITAL_OMICRON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_OMICRON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small pi character entity xml model. */
static wchar_t SMALL_PI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'p', L'g', L'r'};
static wchar_t* SMALL_PI_CHARACTER_ENTITY_XML_MODEL = SMALL_PI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_PI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Pi character entity xml model. */
static wchar_t CAPITAL_PI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'P', L'g', L'r'};
static wchar_t* CAPITAL_PI_CHARACTER_ENTITY_XML_MODEL = CAPITAL_PI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_PI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small rho character entity xml model. */
static wchar_t SMALL_RHO_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'r', L'g', L'r'};
static wchar_t* SMALL_RHO_CHARACTER_ENTITY_XML_MODEL = SMALL_RHO_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_RHO_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Rho character entity xml model. */
static wchar_t CAPITAL_RHO_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'R', L'g', L'r'};
static wchar_t* CAPITAL_RHO_CHARACTER_ENTITY_XML_MODEL = CAPITAL_RHO_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_RHO_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small sigma character entity xml model. */
static wchar_t SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L's', L'g', L'r'};
static wchar_t* SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL = SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Sigma character entity xml model. */
static wchar_t CAPITAL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'S', L'g', L'r'};
static wchar_t* CAPITAL_SIGMA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_SIGMA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The final small sigma character entity xml model. */
static wchar_t FINAL_SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L's', L'f', L'g', L'r'};
static wchar_t* FINAL_SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL = FINAL_SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* FINAL_SMALL_SIGMA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small tau character entity xml model. */
static wchar_t SMALL_TAU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L't', L'g', L'r'};
static wchar_t* SMALL_TAU_CHARACTER_ENTITY_XML_MODEL = SMALL_TAU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_TAU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Tau character entity xml model. */
static wchar_t CAPITAL_TAU_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'T', L'g', L'r'};
static wchar_t* CAPITAL_TAU_CHARACTER_ENTITY_XML_MODEL = CAPITAL_TAU_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_TAU_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small upsilon character entity xml model. */
static wchar_t SMALL_UPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'u', L'g', L'r'};
static wchar_t* SMALL_UPSILON_CHARACTER_ENTITY_XML_MODEL = SMALL_UPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_UPSILON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Upsilon character entity xml model. */
static wchar_t CAPITAL_UPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'U', L'g', L'r'};
static wchar_t* CAPITAL_UPSILON_CHARACTER_ENTITY_XML_MODEL = CAPITAL_UPSILON_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_UPSILON_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_3_INTEGER_MEMORY_MODEL_ARRAY;

/** The small phi character entity xml model. */
static wchar_t SMALL_PHI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'p', L'h', L'g', L'r'};
static wchar_t* SMALL_PHI_CHARACTER_ENTITY_XML_MODEL = SMALL_PHI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_PHI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Phi character entity xml model. */
static wchar_t CAPITAL_PHI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'P', L'H', L'g', L'r'};
static wchar_t* CAPITAL_PHI_CHARACTER_ENTITY_XML_MODEL = CAPITAL_PHI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_PHI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small chi character entity xml model. */
static wchar_t SMALL_CHI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'k', L'h', L'g', L'r'};
static wchar_t* SMALL_CHI_CHARACTER_ENTITY_XML_MODEL = SMALL_CHI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_CHI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Chi character entity xml model. */
static wchar_t CAPITAL_CHI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'K', L'H', L'g', L'r'};
static wchar_t* CAPITAL_CHI_CHARACTER_ENTITY_XML_MODEL = CAPITAL_CHI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_CHI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small psi character entity xml model. */
static wchar_t SMALL_PSI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'p', L's', L'g'; L'r'};
static wchar_t* SMALL_PSI_CHARACTER_ENTITY_XML_MODEL = SMALL_PSI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_PSI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Psi character entity xml model. */
static wchar_t CAPITAL_PSI_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'P', L'S', L'g', L'r'};
static wchar_t* CAPITAL_PSI_CHARACTER_ENTITY_XML_MODEL = CAPITAL_PSI_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_PSI_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The small omega character entity xml model. */
static wchar_t SMALL_OMEGA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'o', L'h', L'g'; L'r'};
static wchar_t* SMALL_OMEGA_CHARACTER_ENTITY_XML_MODEL = SMALL_OMEGA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* SMALL_OMEGA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/** The capital Omega character entity xml model. */
static wchar_t CAPITAL_OMEGA_CHARACTER_ENTITY_XML_MODEL_ARRAY[] = {L'O', L'H', L'g', L'r'};
static wchar_t* CAPITAL_OMEGA_CHARACTER_ENTITY_XML_MODEL = CAPITAL_OMEGA_CHARACTER_ENTITY_XML_MODEL_ARRAY;
static int* CAPITAL_OMEGA_CHARACTER_ENTITY_XML_MODEL_COUNT = NUMBER_4_INTEGER_MEMORY_MODEL_ARRAY;

/* End Thiele, Thomas and Simon, Friedemann */




/* CHARACTER_ENTITY_XML_MODEL_SOURCE */
#endif
