        <div id="navigation">
            <h1>General</h1>
            <a href="http://developer.berlios.de/project/showfiles.php?group_id=669">
                Download
            </a>
            <a href="http://developer.berlios.de/mail/?group_id=669">
                Mailing Lists
            </a>
            <a href="licence/index.shtml">
                Licence Issues
            </a>
            <a href="http://www.gnu.org/gnu/thegnuproject.html">
                Philosophy
            </a>
            <a href="http://developer.berlios.de/project/stats/?group_id=669">
                Activity Statistics
            </a>
            <a href="credits/index.shtml">
                Credits
            </a>
            <h1>Documentation</h1>
            <a href="books/index.shtml">
                Books
            </a>
            <a href="presentations/index.shtml">
                Presentations
            </a>
            <a href="papers/index.shtml">
                Papers
            </a>
            <a href="tutorials/index.shtml">
                Tutorials
            </a>
            <h1>Development</h1>
            <a href="http://developer.berlios.de/bugs/?group_id=669">
                Bug Report
            </a>
            <a href="http://developer.berlios.de/cvs/?group_id=669">
                CVS
            </a>
            <a href="plan/index.shtml">
                Project Plan
            </a>
            <a href="help/index.shtml">
                How to help
            </a>
            <div id="information">
                <a href="http://developer.berlios.de/projects/cybop/">
                    Our project hosted on:<br/>
                    <img src="http://developer.berlios.de/bslogo.php?group_id=669" alt="BerliOS Developer Logo" vspace="2" width="124" height="32" border="1"/>
                </a>
                <a href="http://www.ffii.org/">
                    Fight Software Patents!<br/>
                    <img src="patent_button.png" alt="Eurolinux Petition" vspace="2" border="1"/>
                </a>
                <a href="http://www.resmedicinae.org">
                    Res Medicinae<br/>
                    <img src="res_medicinae.png" alt="Res Medicinae" vspace="2" border="1"/>
                </a>
            </div>
        </div>
