/*
 * Copyright (C) 1999-2012. Christian Heller.
 *
 * This file is part of the Cybernetics Oriented Interpreter (CYBOI).
 *
 * CYBOI is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * CYBOI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CYBOI. If not, see <http://www.gnu.org/licenses/>.
 *
 * Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
 * Christian Heller <christian.heller@tuxtax.de>
 *
 * @version CYBOP 0.11.0 2012-01-01
 * @author Christian Heller <christian.heller@tuxtax.de>
 */

#ifndef NUMERIC_ESCAPE_MODEL_CONSTANT_SOURCE
#define NUMERIC_ESCAPE_MODEL_CONSTANT_SOURCE

#include <stddef.h>

#include "../../../constant/model/cyboi/state/integer_state_cyboi_model.c"

//
// The references 00 to 08 (C0 control characters) are forbidden.
//

/** The horizontal tab numeric escape model. */
static wchar_t HORIZONTAL_TAB_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'0', L'9', L';'};
static wchar_t* HORIZONTAL_TAB_NUMERIC_ESCAPE_MODEL = HORIZONTAL_TAB_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* HORIZONTAL_TAB_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The line feed numeric escape model. */
static wchar_t LINE_FEED_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L';'};
static wchar_t* LINE_FEED_NUMERIC_ESCAPE_MODEL = LINE_FEED_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LINE_FEED_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

//
// The references 11 to 12 (C0 control characters) are forbidden.
//

/** The carriage return numeric escape model. */
static wchar_t CARRIAGE_RETURN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'3', L';'};
static wchar_t* CARRIAGE_RETURN_NUMERIC_ESCAPE_MODEL = CARRIAGE_RETURN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CARRIAGE_RETURN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

//
// The references 14 to 31 (C0 control characters) are forbidden.
//

/** The space   numeric escape model. */
static wchar_t SPACE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'2', L';'};
static wchar_t* SPACE_NUMERIC_ESCAPE_MODEL = SPACE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SPACE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The exclamation mark ! numeric escape model. */
static wchar_t EXCLAMATION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'3', L';'};
static wchar_t* EXCLAMATION_MARK_NUMERIC_ESCAPE_MODEL = EXCLAMATION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* EXCLAMATION_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The quotation mark " numeric escape model. */
static wchar_t QUOTATION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'4', L';'};
static wchar_t* QUOTATION_MARK_NUMERIC_ESCAPE_MODEL = QUOTATION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* QUOTATION_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The number sign # numeric escape model. */
static wchar_t NUMBER_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'5', L';'};
static wchar_t* NUMBER_SIGN_NUMERIC_ESCAPE_MODEL = NUMBER_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* NUMBER_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The dollar sign $ numeric escape model. */
static wchar_t DOLLAR_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'6', L';'};
static wchar_t* DOLLAR_SIGN_NUMERIC_ESCAPE_MODEL = DOLLAR_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DOLLAR_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The percent sign % numeric escape model. */
static wchar_t PERCENT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'7', L';'};
static wchar_t* PERCENT_SIGN_NUMERIC_ESCAPE_MODEL = PERCENT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* PERCENT_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The ampersand & numeric escape model. */
static wchar_t AMPERSAND_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'8', L';'};
static wchar_t* AMPERSAND_NUMERIC_ESCAPE_MODEL = AMPERSAND_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* AMPERSAND_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The apostrophe ' numeric escape model. */
static wchar_t APOSTROPHE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'3', L'9', L';'};
static wchar_t* APOSTROPHE_NUMERIC_ESCAPE_MODEL = APOSTROPHE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* APOSTROPHE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The left parenthesis ( numeric escape model. */
static wchar_t LEFT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'0', L';'};
static wchar_t* LEFT_PARENTHESIS_NUMERIC_ESCAPE_MODEL = LEFT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LEFT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The right parenthesis ) numeric escape model. */
static wchar_t RIGHT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'1', L';'};
static wchar_t* RIGHT_PARENTHESIS_NUMERIC_ESCAPE_MODEL = RIGHT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* RIGHT_PARENTHESIS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The asterisk * numeric escape model. */
static wchar_t ASTERISK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'2', L';'};
static wchar_t* ASTERISK_NUMERIC_ESCAPE_MODEL = ASTERISK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* ASTERISK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The plus sign + numeric escape model. */
static wchar_t PLUS_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'3', L';'};
static wchar_t* PLUS_SIGN_NUMERIC_ESCAPE_MODEL = PLUS_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* PLUS_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The comma , numeric escape model. */
static wchar_t COMMA_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'4', L';'};
static wchar_t* COMMA_NUMERIC_ESCAPE_MODEL = COMMA_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* COMMA_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The hyphen - numeric escape model. */
static wchar_t HYPHEN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'5', L';'};
static wchar_t* HYPHEN_NUMERIC_ESCAPE_MODEL = HYPHEN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* HYPHEN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The period (fullstop, dot) . numeric escape model. */
static wchar_t PERIOD_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'6', L';'};
static wchar_t* PERIOD_NUMERIC_ESCAPE_MODEL = PERIOD_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* PERIOD_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The solidus (slash) / numeric escape model. */
static wchar_t SOLIDUS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'7', L';'};
static wchar_t* SOLIDUS_NUMERIC_ESCAPE_MODEL = SOLIDUS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SOLIDUS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 0 numeric escape model. */
static wchar_t DIGIT_0_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'8', L';'};
static wchar_t* DIGIT_0_NUMERIC_ESCAPE_MODEL = DIGIT_0_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_0_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 1 numeric escape model. */
static wchar_t DIGIT_1_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'4', L'9', L';'};
static wchar_t* DIGIT_1_NUMERIC_ESCAPE_MODEL = DIGIT_1_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_1_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 2 numeric escape model. */
static wchar_t DIGIT_2_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'0', L';'};
static wchar_t* DIGIT_2_NUMERIC_ESCAPE_MODEL = DIGIT_2_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_2_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 3 numeric escape model. */
static wchar_t DIGIT_3_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'1', L';'};
static wchar_t* DIGIT_3_NUMERIC_ESCAPE_MODEL = DIGIT_3_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_3_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 4 numeric escape model. */
static wchar_t DIGIT_4_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'2', L';'};
static wchar_t* DIGIT_4_NUMERIC_ESCAPE_MODEL = DIGIT_4_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_4_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 5 numeric escape model. */
static wchar_t DIGIT_5_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'3', L';'};
static wchar_t* DIGIT_5_NUMERIC_ESCAPE_MODEL = DIGIT_5_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_5_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 6 numeric escape model. */
static wchar_t DIGIT_6_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'4', L';'};
static wchar_t* DIGIT_6_NUMERIC_ESCAPE_MODEL = DIGIT_6_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_6_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 7 numeric escape model. */
static wchar_t DIGIT_7_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'5', L';'};
static wchar_t* DIGIT_7_NUMERIC_ESCAPE_MODEL = DIGIT_7_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_7_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 8 numeric escape model. */
static wchar_t DIGIT_8_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'6', L';'};
static wchar_t* DIGIT_8_NUMERIC_ESCAPE_MODEL = DIGIT_8_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_8_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The digit 9 numeric escape model. */
static wchar_t DIGIT_9_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'7', L';'};
static wchar_t* DIGIT_9_NUMERIC_ESCAPE_MODEL = DIGIT_9_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIGIT_9_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The colon : numeric escape model. */
static wchar_t COLON_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'8', L';'};
static wchar_t* COLON_NUMERIC_ESCAPE_MODEL = COLON_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* COLON_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The semi-colon ; numeric escape model. */
static wchar_t SEMICOLON_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'5', L'9', L';'};
static wchar_t* SEMICOLON_NUMERIC_ESCAPE_MODEL = SEMICOLON_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SEMICOLON_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The less than < numeric escape model. */
static wchar_t LESS_THAN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'0', L';'};
static wchar_t* LESS_THAN_NUMERIC_ESCAPE_MODEL = LESS_THAN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LESS_THAN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The equals sign = numeric escape model. */
static wchar_t EQUALS_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'1', L';'};
static wchar_t* EQUALS_SIGN_NUMERIC_ESCAPE_MODEL = EQUALS_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* EQUALS_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The greater than > numeric escape model. */
static wchar_t GREATER_THAN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'2', L';'};
static wchar_t* GREATER_THAN_NUMERIC_ESCAPE_MODEL = GREATER_THAN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* GREATER_THAN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The question mark ? numeric escape model. */
static wchar_t QUESTION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'3', L';'};
static wchar_t* QUESTION_MARK_NUMERIC_ESCAPE_MODEL = QUESTION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* QUESTION_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The commercial at @ numeric escape model. */
static wchar_t COMMERCIAL_AT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'4', L';'};
static wchar_t* COMMERCIAL_AT_NUMERIC_ESCAPE_MODEL = COMMERCIAL_AT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* COMMERCIAL_AT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter a numeric escape model. */
static wchar_t CAPITAL_LETTER_A_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'5', L';'};
static wchar_t* CAPITAL_LETTER_A_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_A_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_A_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter b numeric escape model. */
static wchar_t CAPITAL_LETTER_B_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'6', L';'};
static wchar_t* CAPITAL_LETTER_B_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_B_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_B_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter c numeric escape model. */
static wchar_t CAPITAL_LETTER_C_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'7', L';'};
static wchar_t* CAPITAL_LETTER_C_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_C_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_C_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter d numeric escape model. */
static wchar_t CAPITAL_LETTER_D_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'8', L';'};
static wchar_t* CAPITAL_LETTER_D_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_D_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_D_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter e numeric escape model. */
static wchar_t CAPITAL_LETTER_E_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'6', L'9', L';'};
static wchar_t* CAPITAL_LETTER_E_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_E_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_E_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter f numeric escape model. */
static wchar_t CAPITAL_LETTER_F_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'0', L';'};
static wchar_t* CAPITAL_LETTER_F_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_F_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_F_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter g numeric escape model. */
static wchar_t CAPITAL_LETTER_G_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'1', L';'};
static wchar_t* CAPITAL_LETTER_G_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_G_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_G_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter h numeric escape model. */
static wchar_t CAPITAL_LETTER_H_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'2', L';'};
static wchar_t* CAPITAL_LETTER_H_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_H_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_H_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter i numeric escape model. */
static wchar_t CAPITAL_LETTER_I_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'3', L';'};
static wchar_t* CAPITAL_LETTER_I_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_I_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_I_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter j numeric escape model. */
static wchar_t CAPITAL_LETTER_J_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'4', L';'};
static wchar_t* CAPITAL_LETTER_J_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_J_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_J_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter k numeric escape model. */
static wchar_t CAPITAL_LETTER_K_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'5', L';'};
static wchar_t* CAPITAL_LETTER_K_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_K_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_K_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter l numeric escape model. */
static wchar_t CAPITAL_LETTER_L_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'6', L';'};
static wchar_t* CAPITAL_LETTER_L_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_L_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_L_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter m numeric escape model. */
static wchar_t CAPITAL_LETTER_M_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'7', L';'};
static wchar_t* CAPITAL_LETTER_M_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_M_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_M_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter n numeric escape model. */
static wchar_t CAPITAL_LETTER_N_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'8', L';'};
static wchar_t* CAPITAL_LETTER_N_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_N_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_N_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter o numeric escape model. */
static wchar_t CAPITAL_LETTER_O_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'7', L'9', L';'};
static wchar_t* CAPITAL_LETTER_O_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_O_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_O_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter p numeric escape model. */
static wchar_t CAPITAL_LETTER_P_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'0', L';'};
static wchar_t* CAPITAL_LETTER_P_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_P_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_P_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter q numeric escape model. */
static wchar_t CAPITAL_LETTER_Q_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'1', L';'};
static wchar_t* CAPITAL_LETTER_Q_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_Q_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_Q_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter r numeric escape model. */
static wchar_t CAPITAL_LETTER_R_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'2', L';'};
static wchar_t* CAPITAL_LETTER_R_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_R_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_R_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter s numeric escape model. */
static wchar_t CAPITAL_LETTER_S_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'3', L';'};
static wchar_t* CAPITAL_LETTER_S_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_S_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_S_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter t numeric escape model. */
static wchar_t CAPITAL_LETTER_T_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'4', L';'};
static wchar_t* CAPITAL_LETTER_T_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_T_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_T_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter u numeric escape model. */
static wchar_t CAPITAL_LETTER_U_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'5', L';'};
static wchar_t* CAPITAL_LETTER_U_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_U_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_U_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter v numeric escape model. */
static wchar_t CAPITAL_LETTER_V_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'6', L';'};
static wchar_t* CAPITAL_LETTER_V_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_V_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_V_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter w numeric escape model. */
static wchar_t CAPITAL_LETTER_W_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'7', L';'};
static wchar_t* CAPITAL_LETTER_W_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_W_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_W_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter x numeric escape model. */
static wchar_t CAPITAL_LETTER_X_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'8', L';'};
static wchar_t* CAPITAL_LETTER_X_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_X_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_X_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter y numeric escape model. */
static wchar_t CAPITAL_LETTER_Y_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'8', L'9', L';'};
static wchar_t* CAPITAL_LETTER_Y_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_Y_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_Y_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital letter z numeric escape model. */
static wchar_t CAPITAL_LETTER_Z_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'0', L';'};
static wchar_t* CAPITAL_LETTER_Z_NUMERIC_ESCAPE_MODEL = CAPITAL_LETTER_Z_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_LETTER_Z_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The left square bracket [ numeric escape model. */
static wchar_t LEFT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'1', L';'};
static wchar_t* LEFT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL = LEFT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LEFT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The reverse solidus (backslash) \ numeric escape model. */
static wchar_t REVERSE_SOLIDUS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'2', L';'};
static wchar_t* REVERSE_SOLIDUS_NUMERIC_ESCAPE_MODEL = REVERSE_SOLIDUS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* REVERSE_SOLIDUS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The right square bracket ] numeric escape model. */
static wchar_t RIGHT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'3', L';'};
static wchar_t* RIGHT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL = RIGHT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* RIGHT_SQUARE_BRACKET_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The caret ^ numeric escape model. */
static wchar_t CARET_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'4', L';'};
static wchar_t* CARET_NUMERIC_ESCAPE_MODEL = CARET_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CARET_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The horizontal bar (underscore) _ numeric escape model. */
static wchar_t HORIZONTAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'5', L';'};
static wchar_t* HORIZONTAL_BAR_NUMERIC_ESCAPE_MODEL = HORIZONTAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* HORIZONTAL_BAR_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The grave accent ` numeric escape model. */
static wchar_t GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'6', L';'};
static wchar_t* GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter a numeric escape model. */
static wchar_t SMALL_LETTER_A_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'7', L';'};
static wchar_t* SMALL_LETTER_A_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_A_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_A_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter b numeric escape model. */
static wchar_t SMALL_LETTER_B_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'8', L';'};
static wchar_t* SMALL_LETTER_B_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_B_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_B_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter c numeric escape model. */
static wchar_t SMALL_LETTER_C_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'9', L'9', L';'};
static wchar_t* SMALL_LETTER_C_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_C_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_C_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_5_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter d numeric escape model. */
static wchar_t SMALL_LETTER_D_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'0', L';'};
static wchar_t* SMALL_LETTER_D_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_D_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_D_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter e numeric escape model. */
static wchar_t SMALL_LETTER_E_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'1', L';'};
static wchar_t* SMALL_LETTER_E_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_E_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_E_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter f numeric escape model. */
static wchar_t SMALL_LETTER_F_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'2', L';'};
static wchar_t* SMALL_LETTER_F_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_F_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_F_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter g numeric escape model. */
static wchar_t SMALL_LETTER_G_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'3', L';'};
static wchar_t* SMALL_LETTER_G_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_G_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_G_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter h numeric escape model. */
static wchar_t SMALL_LETTER_H_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'4', L';'};
static wchar_t* SMALL_LETTER_H_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_H_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_H_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter i numeric escape model. */
static wchar_t SMALL_LETTER_I_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'5', L';'};
static wchar_t* SMALL_LETTER_I_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_I_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_I_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter j numeric escape model. */
static wchar_t SMALL_LETTER_J_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'6', L';'};
static wchar_t* SMALL_LETTER_J_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_J_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_J_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter k numeric escape model. */
static wchar_t SMALL_LETTER_K_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'7', L';'};
static wchar_t* SMALL_LETTER_K_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_K_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_K_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter l numeric escape model. */
static wchar_t SMALL_LETTER_L_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'8', L';'};
static wchar_t* SMALL_LETTER_L_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_L_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_L_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter m numeric escape model. */
static wchar_t SMALL_LETTER_M_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'0', L'9', L';'};
static wchar_t* SMALL_LETTER_M_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_M_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_M_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter n numeric escape model. */
static wchar_t SMALL_LETTER_N_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'0', L';'};
static wchar_t* SMALL_LETTER_N_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_N_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_N_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter o numeric escape model. */
static wchar_t SMALL_LETTER_O_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'1', L';'};
static wchar_t* SMALL_LETTER_O_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_O_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_O_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter p numeric escape model. */
static wchar_t SMALL_LETTER_P_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'2', L';'};
static wchar_t* SMALL_LETTER_P_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_P_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_P_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter q numeric escape model. */
static wchar_t SMALL_LETTER_Q_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'3', L';'};
static wchar_t* SMALL_LETTER_Q_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_Q_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_Q_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter r numeric escape model. */
static wchar_t SMALL_LETTER_R_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'4', L';'};
static wchar_t* SMALL_LETTER_R_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_R_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_R_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter s numeric escape model. */
static wchar_t SMALL_LETTER_S_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'5', L';'};
static wchar_t* SMALL_LETTER_S_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_S_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_S_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter t numeric escape model. */
static wchar_t SMALL_LETTER_T_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'6', L';'};
static wchar_t* SMALL_LETTER_T_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_T_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_T_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter u numeric escape model. */
static wchar_t SMALL_LETTER_U_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'7', L';'};
static wchar_t* SMALL_LETTER_U_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_U_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_U_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter v numeric escape model. */
static wchar_t SMALL_LETTER_V_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'8', L';'};
static wchar_t* SMALL_LETTER_V_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_V_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_V_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter w numeric escape model. */
static wchar_t SMALL_LETTER_W_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'1', L'9', L';'};
static wchar_t* SMALL_LETTER_W_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_W_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_W_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter x numeric escape model. */
static wchar_t SMALL_LETTER_X_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'0', L';'};
static wchar_t* SMALL_LETTER_X_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_X_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_X_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter y numeric escape model. */
static wchar_t SMALL_LETTER_Y_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'1', L';'};
static wchar_t* SMALL_LETTER_Y_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_Y_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_Y_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small letter z numeric escape model. */
static wchar_t SMALL_LETTER_Z_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'2', L';'};
static wchar_t* SMALL_LETTER_Z_NUMERIC_ESCAPE_MODEL = SMALL_LETTER_Z_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_LETTER_Z_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The left curly brace { numeric escape model. */
static wchar_t LEFT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'3', L';'};
static wchar_t* LEFT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL = LEFT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LEFT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The vertical bar | numeric escape model. */
static wchar_t VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'4', L';'};
static wchar_t* VERTICAL_BAR_NUMERIC_ESCAPE_MODEL = VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The right curly brace } numeric escape model. */
static wchar_t RIGHT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'5', L';'};
static wchar_t* RIGHT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL = RIGHT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* RIGHT_CURLY_BRACE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The tilde ~ numeric escape model. */
static wchar_t TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'2', L'6', L';'};
static wchar_t* TILDE_NUMERIC_ESCAPE_MODEL = TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

//
// The reference 127 (DEL character) is forbidden.
//

//
// The references 128 to 159 (C1 control characters) are forbidden.
//

/** The non-breaking space   numeric escape model. */
static wchar_t NON_BREAKING_SPACE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'0', L';'};
static wchar_t* NON_BREAKING_SPACE_NUMERIC_ESCAPE_MODEL = NON_BREAKING_SPACE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* NON_BREAKING_SPACE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The inverted exclamation numeric escape model. */
static wchar_t INVERTED_EXCLAMATION_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'1', L';'};
static wchar_t* INVERTED_EXCLAMATION_NUMERIC_ESCAPE_MODEL = INVERTED_EXCLAMATION_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* INVERTED_EXCLAMATION_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The cent sign numeric escape model. */
static wchar_t CENT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'2', L';'};
static wchar_t* CENT_SIGN_NUMERIC_ESCAPE_MODEL = CENT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CENT_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The pound sterling numeric escape model. */
static wchar_t POUND_STERLING_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'3', L';'};
static wchar_t* POUND_STERLING_NUMERIC_ESCAPE_MODEL = POUND_STERLING_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* POUND_STERLING_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The general currency sign numeric escape model. */
static wchar_t GENERAL_CURRENCY_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'4', L';'};
static wchar_t* GENERAL_CURRENCY_NUMERIC_ESCAPE_MODEL = GENERAL_CURRENCY_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* GENERAL_CURRENCY_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The yen sign numeric escape model. */
static wchar_t YEN_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'5', L';'};
static wchar_t* YEN_SIGN_NUMERIC_ESCAPE_MODEL = YEN_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* YEN_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The broken vertical bar numeric escape model. */
static wchar_t BROKEN_VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'6', L';'};
static wchar_t* BROKEN_VERTICAL_BAR_NUMERIC_ESCAPE_MODEL = BROKEN_VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* BROKEN_VERTICAL_BAR_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The section sign numeric escape model. */
static wchar_t SECTION_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'7', L';'};
static wchar_t* SECTION_SIGN_NUMERIC_ESCAPE_MODEL = SECTION_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SECTION_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The umlaut (dieresis) numeric escape model. */
static wchar_t UMLAUT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'8', L';'};
static wchar_t* UMLAUT_NUMERIC_ESCAPE_MODEL = UMLAUT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* UMLAUT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The copyright numeric escape model. */
static wchar_t COPYRIGHT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'6', L'9', L';'};
static wchar_t* COPYRIGHT_NUMERIC_ESCAPE_MODEL = COPYRIGHT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* COPYRIGHT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The feminine ordinal numeric escape model. */
static wchar_t FEMININE_ORDINAL_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'0', L';'};
static wchar_t* FEMININE_ORDINAL_NUMERIC_ESCAPE_MODEL = FEMININE_ORDINAL_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* FEMININE_ORDINAL_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The left angle quote, guillemotleft numeric escape model. */
static wchar_t LEFT_ANGLE_QUOTE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'1', L';'};
static wchar_t* LEFT_ANGLE_QUOTE_NUMERIC_ESCAPE_MODEL = LEFT_ANGLE_QUOTE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* LEFT_ANGLE_QUOTE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The not sign numeric escape model. */
static wchar_t NOT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'2', L';'};
static wchar_t* NOT_SIGN_NUMERIC_ESCAPE_MODEL = NOT_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* NOT_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The soft hyphen numeric escape model. */
static wchar_t SOFT_HYPHEN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'3', L';'};
static wchar_t* SOFT_HYPHEN_NUMERIC_ESCAPE_MODEL = SOFT_HYPHEN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SOFT_HYPHEN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The registered trademark numeric escape model. */
static wchar_t REGISTERED_TRADEMARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'4', L';'};
static wchar_t* REGISTERED_TRADEMARK_NUMERIC_ESCAPE_MODEL = REGISTERED_TRADEMARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* REGISTERED_TRADEMARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The macron accent numeric escape model. */
static wchar_t MACRON_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'5', L';'};
static wchar_t* MACRON_ACCENT_NUMERIC_ESCAPE_MODEL = MACRON_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* MACRON_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The degree sign numeric escape model. */
static wchar_t DEGREE_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'6', L';'};
static wchar_t* DEGREE_SIGN_NUMERIC_ESCAPE_MODEL = DEGREE_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DEGREE_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The plus or minus numeric escape model. */
static wchar_t PLUS_OR_MINUS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'7', L';'};
static wchar_t* PLUS_OR_MINUS_NUMERIC_ESCAPE_MODEL = PLUS_OR_MINUS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* PLUS_OR_MINUS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The superscript two � numeric escape model. */
static wchar_t SUPERSCRIPT_TWO_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'8', L';'};
static wchar_t* SUPERSCRIPT_TWO_NUMERIC_ESCAPE_MODEL = SUPERSCRIPT_TWO_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SUPERSCRIPT_TWO_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The superscript three � numeric escape model. */
static wchar_t SUPERSCRIPT_THREE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'7', L'9', L';'};
static wchar_t* SUPERSCRIPT_THREE_NUMERIC_ESCAPE_MODEL = SUPERSCRIPT_THREE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SUPERSCRIPT_THREE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The acute accent numeric escape model. */
static wchar_t ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'0', L';'};
static wchar_t* ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The micro sign numeric escape model. */
static wchar_t MICRO_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'1', L';'};
static wchar_t* MICRO_SIGN_NUMERIC_ESCAPE_MODEL = MICRO_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* MICRO_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The paragraph sign � numeric escape model. */
static wchar_t PARAGRAPH_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'2', L';'};
static wchar_t* PARAGRAPH_SIGN_NUMERIC_ESCAPE_MODEL = PARAGRAPH_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* PARAGRAPH_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The middle dot numeric escape model. */
static wchar_t MIDDLE_DOT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'3', L';'};
static wchar_t* MIDDLE_DOT_NUMERIC_ESCAPE_MODEL = MIDDLE_DOT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* MIDDLE_DOT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The cedilla numeric escape model. */
static wchar_t CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'4', L';'};
static wchar_t* CEDILLA_NUMERIC_ESCAPE_MODEL = CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CEDILLA_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The superscript one � numeric escape model. */
static wchar_t SUPERSCRIPT_ONE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'5', L';'};
static wchar_t* SUPERSCRIPT_ONE_NUMERIC_ESCAPE_MODEL = SUPERSCRIPT_ONE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SUPERSCRIPT_ONE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The masculine ordinal numeric escape model. */
static wchar_t MASCULINE_ORDINAL_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'6', L';'};
static wchar_t* MASCULINE_ORDINAL_NUMERIC_ESCAPE_MODEL = MASCULINE_ORDINAL_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* MASCULINE_ORDINAL_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The right angle quote guillemotright numeric escape model. */
static wchar_t RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'7', L';'};
static wchar_t* RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_ESCAPE_MODEL = RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* RIGHT_ANGLE_QUOTE_GUILLEMOTRIGHT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The fraction one-fourth numeric escape model. */
static wchar_t FRACTION_ONE_FOURTH_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'8', L';'};
static wchar_t* FRACTION_ONE_FOURTH_NUMERIC_ESCAPE_MODEL = FRACTION_ONE_FOURTH_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* FRACTION_ONE_FOURTH_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The fraction one-half � numeric escape model. */
static wchar_t FRACTION_ONE_HALF_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'8', L'9', L';'};
static wchar_t* FRACTION_ONE_HALF_NUMERIC_ESCAPE_MODEL = FRACTION_ONE_HALF_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* FRACTION_ONE_HALF_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The fraction three-fourths � numeric escape model. */
static wchar_t FRACTION_THREE_FOURTHS_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'0', L';'};
static wchar_t* FRACTION_THREE_FOURTHS_NUMERIC_ESCAPE_MODEL = FRACTION_THREE_FOURTHS_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* FRACTION_THREE_FOURTHS_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The inverted question mark numeric escape model. */
static wchar_t INVERTED_QUESTION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'1', L';'};
static wchar_t* INVERTED_QUESTION_MARK_NUMERIC_ESCAPE_MODEL = INVERTED_QUESTION_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* INVERTED_QUESTION_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a grave accent numeric escape model. */
static wchar_t CAPITAL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'2', L';'};
static wchar_t* CAPITAL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a acute accent numeric escape model. */
static wchar_t CAPITAL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'3', L';'};
static wchar_t* CAPITAL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a circumflex accent numeric escape model. */
static wchar_t CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'4', L';'};
static wchar_t* CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a tilde numeric escape model. */
static wchar_t CAPITAL_A_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'5', L';'};
static wchar_t* CAPITAL_A_TILDE_NUMERIC_ESCAPE_MODEL = CAPITAL_A_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a umlaut mark (dieresis) numeric escape model. */
static wchar_t CAPITAL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'6', L';'};
static wchar_t* CAPITAL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = CAPITAL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital a ring numeric escape model. */
static wchar_t CAPITAL_A_RING_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'7', L';'};
static wchar_t* CAPITAL_A_RING_NUMERIC_ESCAPE_MODEL = CAPITAL_A_RING_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_A_RING_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital ae dipthong (ligature) numeric escape model. */
static wchar_t CAPITAL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'8', L';'};
static wchar_t* CAPITAL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL = CAPITAL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital c cedilla numeric escape model. */
static wchar_t CAPITAL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'1', L'9', L'9', L';'};
static wchar_t* CAPITAL_C_CEDILLA_NUMERIC_ESCAPE_MODEL = CAPITAL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital e grave accent numeric escape model. */
static wchar_t CAPITAL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'0', L';'};
static wchar_t* CAPITAL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital e acute accent numeric escape model. */
static wchar_t CAPITAL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'1', L';'};
static wchar_t* CAPITAL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital e circumflex accent numeric escape model. */
static wchar_t CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'2', L';'};
static wchar_t* CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital e umlaut mark (dieresis) numeric escape model. */
static wchar_t CAPITAL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'3', L';'};
static wchar_t* CAPITAL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = CAPITAL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital i grave accent numeric escape model. */
static wchar_t CAPITAL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'4', L';'};
static wchar_t* CAPITAL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital i acute accent numeric escape model. */
static wchar_t CAPITAL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'5', L';'};
static wchar_t* CAPITAL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital i circumflex accent numeric escape model. */
static wchar_t CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'6', L';'};
static wchar_t* CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital i umlaut mark (dieresis) numeric escape model. */
static wchar_t CAPITAL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'7', L';'};
static wchar_t* CAPITAL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = CAPITAL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital eth icelandic numeric escape model. */
static wchar_t CAPITAL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'8', L';'};
static wchar_t* CAPITAL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL = CAPITAL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital n tilde numeric escape model. */
static wchar_t CAPITAL_N_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'0', L'9', L';'};
static wchar_t* CAPITAL_N_TILDE_NUMERIC_ESCAPE_MODEL = CAPITAL_N_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_N_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o grave accent numeric escape model. */
static wchar_t CAPITAL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'0', L';'};
static wchar_t* CAPITAL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o acute accent numeric escape model. */
static wchar_t CAPITAL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'1', L';'};
static wchar_t* CAPITAL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o circumflex accent numeric escape model. */
static wchar_t CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'2', L';'};
static wchar_t* CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o tilde numeric escape model. */
static wchar_t CAPITAL_O_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'3', L';'};
static wchar_t* CAPITAL_O_TILDE_NUMERIC_ESCAPE_MODEL = CAPITAL_O_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o umlaut mark (dieresis) numeric escape model. */
static wchar_t CAPITAL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'4', L';'};
static wchar_t* CAPITAL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = CAPITAL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The multiply sign numeric escape model. */
static wchar_t MULTIPLY_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'5', L';'};
static wchar_t* MULTIPLY_SIGN_NUMERIC_ESCAPE_MODEL = MULTIPLY_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* MULTIPLY_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital o slash numeric escape model. */
static wchar_t CAPITAL_O_SLASH_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'6', L';'};
static wchar_t* CAPITAL_O_SLASH_NUMERIC_ESCAPE_MODEL = CAPITAL_O_SLASH_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_O_SLASH_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital u grave accent numeric escape model. */
static wchar_t CAPITAL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'7', L';'};
static wchar_t* CAPITAL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital u acute accent numeric escape model. */
static wchar_t CAPITAL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'8', L';'};
static wchar_t* CAPITAL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital u circumflex accent numeric escape model. */
static wchar_t CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'1', L'9', L';'};
static wchar_t* CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital u umlaut mark (dieresis) numeric escape model. */
static wchar_t CAPITAL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'0', L';'};
static wchar_t* CAPITAL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = CAPITAL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital y acute accent numeric escape model. */
static wchar_t CAPITAL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'1', L';'};
static wchar_t* CAPITAL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = CAPITAL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The capital thorn icelandic numeric escape model. */
static wchar_t CAPITAL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'2', L';'};
static wchar_t* CAPITAL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL = CAPITAL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* CAPITAL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small sharp s german (sz ligature) numeric escape model. */
static wchar_t SMALL_SHARP_S_GERMAN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'3', L';'};
static wchar_t* SMALL_SHARP_S_GERMAN_NUMERIC_ESCAPE_MODEL = SMALL_SHARP_S_GERMAN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_SHARP_S_GERMAN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a grave accent numeric escape model. */
static wchar_t SMALL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'4', L';'};
static wchar_t* SMALL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a acute accent numeric escape model. */
static wchar_t SMALL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'5', L';'};
static wchar_t* SMALL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a circumflex accent numeric escape model. */
static wchar_t SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'6', L';'};
static wchar_t* SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a tilde numeric escape model. */
static wchar_t SMALL_A_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'7', L';'};
static wchar_t* SMALL_A_TILDE_NUMERIC_ESCAPE_MODEL = SMALL_A_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'8', L';'};
static wchar_t* SMALL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small a ring numeric escape model. */
static wchar_t SMALL_A_RING_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'2', L'9', L';'};
static wchar_t* SMALL_A_RING_NUMERIC_ESCAPE_MODEL = SMALL_A_RING_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_A_RING_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small ae dipthong (ligature) numeric escape model. */
static wchar_t SMALL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'0', L';'};
static wchar_t* SMALL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL = SMALL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_AE_DIPTHONG_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small c cedilla numeric escape model. */
static wchar_t SMALL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'1', L';'};
static wchar_t* SMALL_C_CEDILLA_NUMERIC_ESCAPE_MODEL = SMALL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_C_CEDILLA_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small e grave accent numeric escape model. */
static wchar_t SMALL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'2', L';'};
static wchar_t* SMALL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_E_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small e acute accent numeric escape model. */
static wchar_t SMALL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'3', L';'};
static wchar_t* SMALL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_E_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small e circumflex accent numeric escape model. */
static wchar_t SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'4', L';'};
static wchar_t* SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_E_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small e umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'5', L';'};
static wchar_t* SMALL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_E_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small i grave accent numeric escape model. */
static wchar_t SMALL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'6', L';'};
static wchar_t* SMALL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_I_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small i acute accent numeric escape model. */
static wchar_t SMALL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'7', L';'};
static wchar_t* SMALL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_I_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small i circumflex accent numeric escape model. */
static wchar_t SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'8', L';'};
static wchar_t* SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_I_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small i umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'3', L'9', L';'};
static wchar_t* SMALL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_I_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small eth icelandic numeric escape model. */
static wchar_t SMALL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'0', L';'};
static wchar_t* SMALL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL = SMALL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_ETH_ICELANDIC_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small n tilde numeric escape model. */
static wchar_t SMALL_N_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'1', L';'};
static wchar_t* SMALL_N_TILDE_NUMERIC_ESCAPE_MODEL = SMALL_N_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_N_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o grave accent numeric escape model. */
static wchar_t SMALL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'2', L';'};
static wchar_t* SMALL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o acute accent numeric escape model. */
static wchar_t SMALL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'3', L';'};
static wchar_t* SMALL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o circumflex accent numeric escape model. */
static wchar_t SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'4', L';'};
static wchar_t* SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o tilde numeric escape model. */
static wchar_t SMALL_O_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'5', L';'};
static wchar_t* SMALL_O_TILDE_NUMERIC_ESCAPE_MODEL = SMALL_O_TILDE_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_TILDE_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'6', L';'};
static wchar_t* SMALL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The division sign numeric escape model. */
static wchar_t DIVISION_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'7', L';'};
static wchar_t* DIVISION_SIGN_NUMERIC_ESCAPE_MODEL = DIVISION_SIGN_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* DIVISION_SIGN_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small o slash numeric escape model. */
static wchar_t SMALL_O_SLASH_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'8', L';'};
static wchar_t* SMALL_O_SLASH_NUMERIC_ESCAPE_MODEL = SMALL_O_SLASH_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_O_SLASH_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small u grave accent numeric escape model. */
static wchar_t SMALL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'4', L'9', L';'};
static wchar_t* SMALL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_U_GRAVE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small u acute accent numeric escape model. */
static wchar_t SMALL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'0', L';'};
static wchar_t* SMALL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_U_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small u circumflex accent numeric escape model. */
static wchar_t SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'1', L';'};
static wchar_t* SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_U_CIRCUMFLEX_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small u umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'2', L';'};
static wchar_t* SMALL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_U_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small y acute accent numeric escape model. */
static wchar_t SMALL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'3', L';'};
static wchar_t* SMALL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL = SMALL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_Y_ACUTE_ACCENT_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small thorn icelandic numeric escape model. */
static wchar_t SMALL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'4', L';'};
static wchar_t* SMALL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL = SMALL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_THORN_ICELANDIC_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

/** The small y umlaut mark (dieresis) numeric escape model. */
static wchar_t SMALL_Y_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY[] = {L'&', L'#', L'2', L'5', L'5', L';'};
static wchar_t* SMALL_Y_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL = SMALL_Y_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_ARRAY;
static int* SMALL_Y_UMLAUT_MARK_NUMERIC_ESCAPE_MODEL_COUNT = NUMBER_6_INTEGER_STATE_CYBOI_MODEL_ARRAY;

//
// The references 55296 to 57343 (xD800–xDFFF, the UTF-16 surrogate halves) are forbidden.
//

/* NUMERIC_ESCAPE_MODEL_CONSTANT_SOURCE */
#endif
