;***************************************************************************************************
;************************ ########          ######    **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ########         ###  ###   **********************************************
;************************ ##     ###       ########   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ##     ###       ###  ###   **********************************************
;************************ ########         ###  ###   **********************************************
;***************************************************************************************************

[Default]
elementsFile = D:/cyboldesigner/widget/elements.xml