#
# Copyright (C) 1999-2013. Christian Heller.
#
# This file specifies directories and files to be considered in the build process.
#
# Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
# CYBOP Developers <cybop-developers@nongnu.org>
#
# @version CYBOP 0.15.0 2013-09-22
# @author Didier Link <didier@famille-link.fr>
# @author Christian Heller <christian.heller@tuxtax.de>
#

# CAUTION! Do NOT write directory names with a slash "/" at the end.
# If doing so, the directory names would be added twice,
# e.g. "cybop/examples/examples/" which is NOT wanted.
SUBDIRS = controller

EXTRA_DIST = applicator constant executor logger tester variable architecture.odp architecture.pdf architecture.png architecture.xmi Makefile.am pipeline.png
