/*
 * Copyright (C) 1999-2012. Christian Heller.
 *
 * This file is part of the Cybernetics Oriented Interpreter (CYBOI).
 *
 * CYBOI is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * CYBOI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CYBOI. If not, see <http://www.gnu.org/licenses/>.
 *
 * Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
 * Christian Heller <christian.heller@tuxtax.de>
 *
 * @version CYBOP 0.12.0 2012-08-22
 * @author Christian Heller <christian.heller@tuxtax.de>
 */

#ifndef ISO_8859_15_CHARACTER_CODE_MODEL_CONSTANT_SOURCE
#define ISO_8859_15_CHARACTER_CODE_MODEL_CONSTANT_SOURCE

#include <stddef.h>

#include "../../../../constant/model/character_code/ascii/ascii_character_code_model.c"
#include "../../../../constant/model/character_code/iso_6429/c1_iso_6429_character_code_model.c"

//
// A "Character Set" consists of three parts:
// - Character Repertoire: a, b, c etc., e.g. ISO 8859-1 with 256 characters and Unicode with ~ 1 Mio. characters
// - Character Code: table assigning numbers, e.g. a = 97, b = 98, c = 99 etc.
// - Character Encoding: storing code numbers in Bytes, e.g. 97 = 01100001, 98 = 01100010, 99 = 01100011 etc.
//

//
// ISO/IEC 8859 is a joint ISO and IEC series of standards for 8-bit character encodings.
// The series of standards consists of numbered parts, such as ISO/IEC 8859-1, ISO/IEC 8859-2, etc.
// There are 15 parts, excluding the abandoned ISO/IEC 8859-12.
// The ISO working group maintaining this series of standards has been disbanded.
// ISO/IEC 8859 parts 1, 2, 3, and 4 were originally Ecma International standard ECMA-94.
//
// While "ISO/IEC 8859" (without hyphen) does NOT define
// any characters for ranges 0x00-0x1F and 0x7F-0x9F,
// the "ISO-8859" (WITH hyphen and WITHOUT "IEC") standard
// registered with the IANA specifies non-printable
// control characters within these FREE areas.
// Therefore, both are related and do NOT conflict.
//
// For easier handling, both are merged here, so that
// cyboi is able to handle printable characters as defined
// in "ISO/IEC 8859" AS WELL AS control characters of "ISO-8859".
//
// This file contains ISO-8859-15 character code constants:
// Latin-9
//

//
// The ascii characters in range 0x00-0x7F are NOT repeated here
//

//
// The non-printable control characters in range 0x80-0x9F
// which are defined by "ISO-8859" but not "ISO/IEC 8859"
//

/**
 * The padding character iso-8859-15 character code model. U+0080
 *
 * Listed as XXX in Unicode. Not part of ISO/IEC 6429 (ECMA-48).
 */
static char* PADDING_CHARACTER_ISO_8859_15_CHARACTER_CODE_MODEL = PADDING_CHARACTER_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/**
 * The high octet preset iso-8859-15 character code model. U+0081
 *
 * Listed as XXX in Unicode. Not part of ISO/IEC 6429 (ECMA-48).
 */
static char* HIGH_OCTET_PRESET_ISO_8859_15_CHARACTER_CODE_MODEL = HIGH_OCTET_PRESET_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The break permitted here iso-8859-15 character code model. U+0082 */
static char* BREAK_PERMITTED_HERE_ISO_8859_15_CHARACTER_CODE_MODEL = BREAK_PERMITTED_HERE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The no break here iso-8859-15 character code model. U+0083 */
static char* NO_BREAK_HERE_ISO_8859_15_CHARACTER_CODE_MODEL = NO_BREAK_HERE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The index iso-8859-15 character code model. U+0084 */
static char* INDEX_ISO_8859_15_CHARACTER_CODE_MODEL = INDEX_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The next line iso-8859-15 character code model. U+0085 */
static char* NEXT_LINE_ISO_8859_15_CHARACTER_CODE_MODEL = NEXT_LINE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The start of selected area iso-8859-15 character code model. U+0086 */
static char* START_OF_SELECTED_AREA_ISO_8859_15_CHARACTER_CODE_MODEL = START_OF_SELECTED_AREA_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The end of selected area iso-8859-15 character code model. U+0087 */
static char* END_OF_SELECTED_AREA_ISO_8859_15_CHARACTER_CODE_MODEL = END_OF_SELECTED_AREA_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The character tabulation set iso-8859-15 character code model. U+0088 */
static char* CHARACTER_TABULATION_SET_ISO_8859_15_CHARACTER_CODE_MODEL = CHARACTER_TABULATION_SET_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The character tabulation with justification iso-8859-15 character code model. U+0089 */
static char* CHARACTER_TABULATION_WITH_JUSTIFICATION_ISO_8859_15_CHARACTER_CODE_MODEL = CHARACTER_TABULATION_WITH_JUSTIFICATION_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The line tabulation set iso-8859-15 character code model. U+008A */
static char* LINE_TABULATION_SET_ISO_8859_15_CHARACTER_CODE_MODEL = LINE_TABULATION_SET_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The partial line forward iso-8859-15 character code model. U+008B */
static char* PARTIAL_LINE_FORWARD_ISO_8859_15_CHARACTER_CODE_MODEL = PARTIAL_LINE_FORWARD_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The partial line backward iso-8859-15 character code model. U+008C */
static char* PARTIAL_LINE_BACKWARD_ISO_8859_15_CHARACTER_CODE_MODEL = PARTIAL_LINE_BACKWARD_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The reverse line feed iso-8859-15 character code model. U+008D */
static char* REVERSE_LINE_FEED_ISO_8859_15_CHARACTER_CODE_MODEL = REVERSE_LINE_FEED_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The single-shift two iso-8859-15 character code model. U+008E */
static char* SINGLE_SHIFT_TWO_ISO_8859_15_CHARACTER_CODE_MODEL = SINGLE_SHIFT_TWO_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The single-shift three iso-8859-15 character code model. U+008F */
static char* SINGLE_SHIFT_THREE_ISO_8859_15_CHARACTER_CODE_MODEL = SINGLE_SHIFT_THREE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The device control string iso-8859-15 character code model. U+0090 */
static char* DEVICE_CONTROL_STRING_ISO_8859_15_CHARACTER_CODE_MODEL = DEVICE_CONTROL_STRING_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The private use one iso-8859-15 character code model. U+0091 */
static char* PRIVATE_USE_ONE_ISO_8859_15_CHARACTER_CODE_MODEL = PRIVATE_USE_ONE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The private use two iso-8859-15 character code model. U+0092 */
static char* PRIVATE_USE_TWO_ISO_8859_15_CHARACTER_CODE_MODEL = PRIVATE_USE_TWO_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The set transmit state iso-8859-15 character code model. U+0093 */
static char* SET_TRANSMIT_STATE_ISO_8859_15_CHARACTER_CODE_MODEL = SET_TRANSMIT_STATE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The cancel character iso-8859-15 character code model. U+0094 */
static char* CANCEL_CHARACTER_ISO_8859_15_CHARACTER_CODE_MODEL = CANCEL_CHARACTER_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The message waiting iso-8859-15 character code model. U+0095 */
static char* MESSAGE_WAITING_ISO_8859_15_CHARACTER_CODE_MODEL = MESSAGE_WAITING_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The start of guarded area iso-8859-15 character code model. U+0096 */
static char* START_OF_GUARDED_AREA_ISO_8859_15_CHARACTER_CODE_MODEL = START_OF_GUARDED_AREA_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The end of guarded area iso-8859-15 character code model. U+0097 */
static char* END_OF_GUARDED_AREA_ISO_8859_15_CHARACTER_CODE_MODEL = END_OF_GUARDED_AREA_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The start of string iso-8859-15 character code model. U+0098 */
static char* START_OF_STRING_ISO_8859_15_CHARACTER_CODE_MODEL = START_OF_STRING_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/**
 * The single graphic character introducer iso-8859-15 character code model. U+0099
 *
 * Listed as XXX in Unicode. Not part of ISO/IEC 6429.
 */
static char* SINGLE_GRAPHIC_CHARACTER_INTRODUCER_ISO_8859_15_CHARACTER_CODE_MODEL = SINGLE_GRAPHIC_CHARACTER_INTRODUCER_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The single character introducer iso-8859-15 character code model. U+009A */
static char* SINGLE_CHARACTER_INTRODUCER_ISO_8859_15_CHARACTER_CODE_MODEL = SINGLE_CHARACTER_INTRODUCER_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The control sequence introducer iso-8859-15 character code model. U+009B */
static char* CONTROL_SEQUENCE_INTRODUCER_ISO_8859_15_CHARACTER_CODE_MODEL = CONTROL_SEQUENCE_INTRODUCER_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The string terminator iso-8859-15 character code model. U+009C */
static char* STRING_TERMINATOR_ISO_8859_15_CHARACTER_CODE_MODEL = STRING_TERMINATOR_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The operating system command iso-8859-15 character code model. U+009D */
static char* OPERATING_SYSTEM_COMMAND_ISO_8859_15_CHARACTER_CODE_MODEL = OPERATING_SYSTEM_COMMAND_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The privacy message iso-8859-15 character code model. U+009E */
static char* PRIVACY_MESSAGE_ISO_8859_15_CHARACTER_CODE_MODEL = PRIVACY_MESSAGE_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

/** The application program commandiso-8859-15 character code model. U+009F */
static char* APPLICATION_PROGRAM_COMMAND_ISO_8859_15_CHARACTER_CODE_MODEL = APPLICATION_PROGRAM_COMMAND_C1_ISO_6429_CHARACTER_CODE_MODEL_ARRAY;

//
// The printable characters in range 0xA0-0xFF
//

/** The no-break space iso-8859-15 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_15_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A1 */
static char INVERTED_EXCLAMATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA1};
static char* INVERTED_EXCLAMATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL = INVERTED_EXCLAMATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A2 */
static char CENT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA2};
static char* CENT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = CENT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A3 */
static char POUND_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA3};
static char* POUND_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = POUND_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A4 */
static char EURO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA4};
static char* EURO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = EURO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A5 */
static char YEN_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA5};
static char* YEN_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = YEN_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A6 */
static char LATIN_CAPITAL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA6};
static char* LATIN_CAPITAL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A7 */
static char SECTION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA7};
static char* SECTION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = SECTION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A8 */
static char LATIN_SMALL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA8};
static char* LATIN_SMALL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_S_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00A9 */
static char COPYRIGHT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xA9};
static char* COPYRIGHT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = COPYRIGHT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AA */
static char FEMININE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAA};
static char* FEMININE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL = FEMININE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AB */
static char LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAB};
static char* LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL = LEFT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AC */
static char NOT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAC};
static char* NOT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = NOT_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AD */
static char SOFT_HYPHEN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAD};
static char* SOFT_HYPHEN_ISO_8859_15_CHARACTER_CODE_MODEL = SOFT_HYPHEN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AE */
static char REGISTERED_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAE};
static char* REGISTERED_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = REGISTERED_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00AF */
static char MACRON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xAF};
static char* MACRON_ISO_8859_15_CHARACTER_CODE_MODEL = MACRON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B0 */
static char DEGREE_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB0};
static char* DEGREE_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = DEGREE_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B1 */
static char PLUS_MINUS_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB1};
static char* PLUS_MINUS_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = PLUS_MINUS_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B2 */
static char SUPERSCRIPT_TWO_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB2};
static char* SUPERSCRIPT_TWO_ISO_8859_15_CHARACTER_CODE_MODEL = SUPERSCRIPT_TWO_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B3 */
static char SUPERSCRIPT_THREE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB3};
static char* SUPERSCRIPT_THREE_ISO_8859_15_CHARACTER_CODE_MODEL = SUPERSCRIPT_THREE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B4 */
static char LATIN_CAPITAL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB4};
static char* LATIN_CAPITAL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B5 */
static char MICRO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB5};
static char* MICRO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = MICRO_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B6 */
static char PILCROW_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB6};
static char* PILCROW_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = PILCROW_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B7 */
static char MIDDLE_DOT_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB7};
static char* MIDDLE_DOT_ISO_8859_15_CHARACTER_CODE_MODEL = MIDDLE_DOT_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B8 */
static char LATIN_SMALL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB8};
static char* LATIN_SMALL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Z_WITH_CARON_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00B9 */
static char SUPERSCRIPT_ONE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xB9};
static char* SUPERSCRIPT_ONE_ISO_8859_15_CHARACTER_CODE_MODEL = SUPERSCRIPT_ONE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BA */
static char MASCULINE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBA};
static char* MASCULINE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL = MASCULINE_ORDINAL_INDICATOR_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BB */
static char RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBB};
static char* RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL = RIGHT_POINTING_DOUBLE_ANGLE_QUOTATION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BC */
static char LATIN_CAPITAL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBC};
static char* LATIN_CAPITAL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BD */
static char LATIN_SMALL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBD};
static char* LATIN_SMALL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LIGATURE_OE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BE */
static char LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBE};
static char* LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00BF */
static char INVERTED_QUESTION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xBF};
static char* INVERTED_QUESTION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL = INVERTED_QUESTION_MARK_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C0 */
static char LATIN_CAPITAL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC0};
static char* LATIN_CAPITAL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C1 */
static char LATIN_CAPITAL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC1};
static char* LATIN_CAPITAL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C2 */
static char LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC2};
static char* LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C3 */
static char LATIN_CAPITAL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC3};
static char* LATIN_CAPITAL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C4 */
static char LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC4};
static char* LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C5 */
static char LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC5};
static char* LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C6 */
static char LATIN_CAPITAL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC6};
static char* LATIN_CAPITAL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C7 */
static char LATIN_CAPITAL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC7};
static char* LATIN_CAPITAL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C8 */
static char LATIN_CAPITAL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC8};
static char* LATIN_CAPITAL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00C9 */
static char LATIN_CAPITAL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xC9};
static char* LATIN_CAPITAL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CA */
static char LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCA};
static char* LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CB */
static char LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCB};
static char* LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CC */
static char LATIN_CAPITAL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCC};
static char* LATIN_CAPITAL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CD */
static char LATIN_CAPITAL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCD};
static char* LATIN_CAPITAL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CE */
static char LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCE};
static char* LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00CF */
static char LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xCF};
static char* LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D0 */
static char LATIN_CAPITAL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD0};
static char* LATIN_CAPITAL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D1 */
static char LATIN_CAPITAL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD1};
static char* LATIN_CAPITAL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D2 */
static char LATIN_CAPITAL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD2};
static char* LATIN_CAPITAL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D3 */
static char LATIN_CAPITAL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD3};
static char* LATIN_CAPITAL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D4 */
static char LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD4};
static char* LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D5 */
static char LATIN_CAPITAL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD5};
static char* LATIN_CAPITAL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D6 */
static char LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD6};
static char* LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D7 */
static char MULTIPLICATION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD7};
static char* MULTIPLICATION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = MULTIPLICATION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D8 */
static char LATIN_CAPITAL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD8};
static char* LATIN_CAPITAL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00D9 */
static char LATIN_CAPITAL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xD9};
static char* LATIN_CAPITAL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DA */
static char LATIN_CAPITAL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDA};
static char* LATIN_CAPITAL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DB */
static char LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDB};
static char* LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DC */
static char LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDC};
static char* LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DD */
static char LATIN_CAPITAL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDD};
static char* LATIN_CAPITAL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DE */
static char LATIN_CAPITAL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDE};
static char* LATIN_CAPITAL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00DF */
static char LATIN_SMALL_LETTER_SHARP_S_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xDF};
static char* LATIN_SMALL_LETTER_SHARP_S_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_SHARP_S_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E0 */
static char LATIN_SMALL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE0};
static char* LATIN_SMALL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E1 */
static char LATIN_SMALL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE1};
static char* LATIN_SMALL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E2 */
static char LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE2};
static char* LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E3 */
static char LATIN_SMALL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE3};
static char* LATIN_SMALL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E4 */
static char LATIN_SMALL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE4};
static char* LATIN_SMALL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E5 */
static char LATIN_SMALL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE5};
static char* LATIN_SMALL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_WITH_RING_ABOVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E6 */
static char LATIN_SMALL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE6};
static char* LATIN_SMALL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_AE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E7 */
static char LATIN_SMALL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE7};
static char* LATIN_SMALL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_C_WITH_CEDILLA_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E8 */
static char LATIN_SMALL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE8};
static char* LATIN_SMALL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_E_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00E9 */
static char LATIN_SMALL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xE9};
static char* LATIN_SMALL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_E_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00EA */
static char LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xEA};
static char* LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_E_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00EB */
static char LATIN_SMALL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xEB};
static char* LATIN_SMALL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_E_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00EC */
static char LATIN_SMALL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xEC};
static char* LATIN_SMALL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_I_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00ED */
static char LATIN_SMALL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xED};
static char* LATIN_SMALL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_I_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00EE */
static char LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xEE};
static char* LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_I_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00EF */
static char LATIN_SMALL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xEF};
static char* LATIN_SMALL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_I_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F0 */
static char LATIN_SMALL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF0};
static char* LATIN_SMALL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_ETH_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F1 */
static char LATIN_SMALL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF1};
static char* LATIN_SMALL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_N_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F2 */
static char LATIN_SMALL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF2};
static char* LATIN_SMALL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F3 */
static char LATIN_SMALL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF3};
static char* LATIN_SMALL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F4 */
static char LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF4};
static char* LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F5 */
static char LATIN_SMALL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF5};
static char* LATIN_SMALL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_TILDE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F6 */
static char LATIN_SMALL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF6};
static char* LATIN_SMALL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F7 */
static char DIVISION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF7};
static char* DIVISION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL = DIVISION_SIGN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F8 */
static char LATIN_SMALL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF8};
static char* LATIN_SMALL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_WITH_STROKE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00F9 */
static char LATIN_SMALL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xF9};
static char* LATIN_SMALL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_U_WITH_GRAVE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FA */
static char LATIN_SMALL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFA};
static char* LATIN_SMALL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_U_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FB */
static char LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFB};
static char* LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_U_WITH_CIRCUMFLEX_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FC */
static char LATIN_SMALL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFC};
static char* LATIN_SMALL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_U_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FD */
static char LATIN_SMALL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFD};
static char* LATIN_SMALL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Y_WITH_ACUTE_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FE */
static char LATIN_SMALL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFE};
static char* LATIN_SMALL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_THORN_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/** The no-break space iso-8859-15 character code model. U+00FF */
static char LATIN_SMALL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY[] = {0xFF};
static char* LATIN_SMALL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Y_WITH_DIAERESIS_ISO_8859_15_CHARACTER_CODE_MODEL_ARRAY;

/* ISO_8859_15_CHARACTER_CODE_MODEL_CONSTANT_SOURCE */
#endif
