/*
 * Copyright (C) 1999-2012. Christian Heller.
 *
 * This file is part of the Cybernetics Oriented Interpreter (CYBOI).
 *
 * CYBOI is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * CYBOI is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with CYBOI. If not, see <http://www.gnu.org/licenses/>.
 *
 * Cybernetics Oriented Programming (CYBOP) <http://www.cybop.org/>
 * Christian Heller <christian.heller@tuxtax.de>
 *
 * @version CYBOP 0.12.0 2012-08-22
 * @author Christian Heller <christian.heller@tuxtax.de>
 */

#ifndef ISO_8859_11_CHARACTER_CODE_MODEL_CONSTANT_SOURCE
#define ISO_8859_11_CHARACTER_CODE_MODEL_CONSTANT_SOURCE

#include <stddef.h>

#include "../../../../constant/model/character_code/ascii/ascii_character_code_model.c"

//
// A "Character Set" consists of three parts:
// - Character Repertoire: a, b, c etc., e.g. ISO 8859-1 with 256 characters and Unicode with ~ 1 Mio. characters
// - Character Code: table assigning numbers, e.g. a = 97, b = 98, c = 99 etc.
// - Character Encoding: storing code numbers in Bytes, e.g. 97 = 01100001, 98 = 01100010, 99 = 01100011 etc.
//

//
// ISO/IEC 8859 is a joint ISO and IEC series of standards for 8-bit character encodings.
// The series of standards consists of numbered parts, such as ISO/IEC 8859-1, ISO/IEC 8859-2, etc.
// There are 15 parts, excluding the abandoned ISO/IEC 8859-12.
// The ISO working group maintaining this series of standards has been disbanded.
// ISO/IEC 8859 parts 1, 2, 3, and 4 were originally Ecma International standard ECMA-94.
//
// While "ISO/IEC 8859" (without hyphen) does NOT define
// any characters for ranges 0x00-0x1F and 0x7F-0x9F,
// the "ISO-8859" (WITH hyphen and WITHOUT "IEC") standard
// registered with the IANA specifies non-printable
// control characters within these FREE areas.
// Therefore, both are related and do NOT conflict.
//
// CAUTION! The "ISO/IEC 8859-11" did NOT get assigned an
// IANA charset "ISO-8859-11", presumably because it was
// almost identical to the Thai Industrial Standard (TIS) 620.
//
// This file contains ISO/IEC 8859-11 character code constants:
// Latin/Thai
//

//
// The non-printable control characters in range 0x00-0x1F
// are NOT defined, since an "ISO-8859-11" does NOT exist.
//

//
// The printable characters in range 0x20-0x7E.
//

/** The space iso-8859-11 character code model. U+0020 */
static char* SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = SPACE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The exclamation mark iso-8859-11 character code model. U+0021 */
static char* EXCLAMATION_MARK_ISO_8859_11_CHARACTER_CODE_MODEL = EXCLAMATION_MARK_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The quotation mark iso-8859-11 character code model. U+0022 */
static char* QUOTATION_MARK_ISO_8859_11_CHARACTER_CODE_MODEL = QUOTATION_MARK_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The number sign iso-8859-11 character code model. U+0023 */
static char* NUMBER_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = NUMBER_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The dollar sign iso-8859-11 character code model. U+0024 */
static char* DOLLAR_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = DOLLAR_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The percent sign iso-8859-11 character code model. U+0025 */
static char* PERCENT_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = PERCENT_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The ampersand iso-8859-11 character code model. U+0026 */
static char* AMPERSAND_ISO_8859_11_CHARACTER_CODE_MODEL = AMPERSAND_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The apostrophe iso-8859-11 character code model. U+0027 */
static char* APOSTROPHE_ISO_8859_11_CHARACTER_CODE_MODEL = APOSTROPHE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The left parenthesis iso-8859-11 character code model. U+0028 */
static char* LEFT_PARENTHESIS_ISO_8859_11_CHARACTER_CODE_MODEL = LEFT_PARENTHESIS_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The right parenthesis iso-8859-11 character code model. U+0029 */
static char* RIGHT_PARENTHESIS_ISO_8859_11_CHARACTER_CODE_MODEL = RIGHT_PARENTHESIS_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The asterisk iso-8859-11 character code model. U+002A */
static char* ASTERISK_ISO_8859_11_CHARACTER_CODE_MODEL = ASTERISK_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The plus sign iso-8859-11 character code model. U+002B */
static char* PLUS_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = PLUS_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The comma iso-8859-11 character code model. U+002C */
static char* COMMA_ISO_8859_11_CHARACTER_CODE_MODEL = COMMA_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The hyphen minus iso-8859-11 character code model. U+002D */
static char* HYPHEN_MINUS_ISO_8859_11_CHARACTER_CODE_MODEL = HYPHEN_MINUS_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The full stop iso-8859-11 character code model. U+002E */
static char* FULL_STOP_ISO_8859_11_CHARACTER_CODE_MODEL = FULL_STOP_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The solidus iso-8859-11 character code model. U+002F */
static char* SOLIDUS_ISO_8859_11_CHARACTER_CODE_MODEL = SOLIDUS_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit zero iso-8859-11 character code model. U+0030 */
static char* DIGIT_ZERO_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_ZERO_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit one iso-8859-11 character code model. U+0031 */
static char* DIGIT_ONE_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_ONE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit two iso-8859-11 character code model. U+0032 */
static char* DIGIT_TWO_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_TWO_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit three iso-8859-11 character code model. U+0033 */
static char* DIGIT_THREE_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_THREE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit four iso-8859-11 character code model. U+0034 */
static char* DIGIT_FOUR_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_FOUR_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit five iso-8859-11 character code model. U+0035 */
static char* DIGIT_FIVE_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_FIVE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit six iso-8859-11 character code model. U+0036 */
static char* DIGIT_SIX_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_SIX_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit seven iso-8859-11 character code model. U+0037 */
static char* DIGIT_SEVEN_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_SEVEN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit eight iso-8859-11 character code model. U+0038 */
static char* DIGIT_EIGHT_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_EIGHT_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The digit nine iso-8859-11 character code model. U+0039 */
static char* DIGIT_NINE_ISO_8859_11_CHARACTER_CODE_MODEL = DIGIT_NINE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The colon iso-8859-11 character code model. U+003A */
static char* COLON_ISO_8859_11_CHARACTER_CODE_MODEL = COLON_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The semicolon iso-8859-11 character code model. U+003B */
static char* SEMICOLON_ISO_8859_11_CHARACTER_CODE_MODEL = SEMICOLON_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The less than sign iso-8859-11 character code model. U+003C */
static char* LESS_THAN_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = LESS_THAN_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The equals sign iso-8859-11 character code model. U+003D */
static char* EQUALS_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = EQUALS_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The greater than sign iso-8859-11 character code model. U+003E */
static char* GREATER_THAN_SIGN_ISO_8859_11_CHARACTER_CODE_MODEL = GREATER_THAN_SIGN_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The question mark iso-8859-11 character code model. U+003F */
static char* QUESTION_MARK_ISO_8859_11_CHARACTER_CODE_MODEL = QUESTION_MARK_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The commercial at iso-8859-11 character code model. U+0040 */
static char* COMMERCIAL_AT_ISO_8859_11_CHARACTER_CODE_MODEL = COMMERCIAL_AT_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter a iso-8859-11 character code model. U+0041 */
static char* LATIN_CAPITAL_LETTER_A_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_A_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter b iso-8859-11 character code model. U+0042 */
static char* LATIN_CAPITAL_LETTER_B_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_B_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter c iso-8859-11 character code model. U+0043 */
static char* LATIN_CAPITAL_LETTER_C_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_C_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter d iso-8859-11 character code model. U+0044 */
static char* LATIN_CAPITAL_LETTER_D_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_D_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter e iso-8859-11 character code model. U+0045 */
static char* LATIN_CAPITAL_LETTER_E_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_E_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter f iso-8859-11 character code model. U+0046 */
static char* LATIN_CAPITAL_LETTER_F_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_F_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter g iso-8859-11 character code model. U+0047 */
static char* LATIN_CAPITAL_LETTER_G_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_G_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter h iso-8859-11 character code model. U+0048 */
static char* LATIN_CAPITAL_LETTER_H_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_H_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter i iso-8859-11 character code model. U+0049 */
static char* LATIN_CAPITAL_LETTER_I_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_I_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter j iso-8859-11 character code model. U+004A */
static char* LATIN_CAPITAL_LETTER_J_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_J_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter k iso-8859-11 character code model. U+004B */
static char* LATIN_CAPITAL_LETTER_K_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_K_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter l iso-8859-11 character code model. U+004C */
static char* LATIN_CAPITAL_LETTER_L_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_L_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter m iso-8859-11 character code model. U+004D */
static char* LATIN_CAPITAL_LETTER_M_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_M_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter n iso-8859-11 character code model. U+004E */
static char* LATIN_CAPITAL_LETTER_N_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_N_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter o iso-8859-11 character code model. U+004F */
static char* LATIN_CAPITAL_LETTER_O_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_O_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter p iso-8859-11 character code model. U+0050 */
static char* LATIN_CAPITAL_LETTER_P_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_P_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter q iso-8859-11 character code model. U+0051 */
static char* LATIN_CAPITAL_LETTER_Q_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Q_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter r iso-8859-11 character code model. U+0052 */
static char* LATIN_CAPITAL_LETTER_R_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_R_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter s iso-8859-11 character code model. U+0053 */
static char* LATIN_CAPITAL_LETTER_S_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_S_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter t iso-8859-11 character code model. U+0054 */
static char* LATIN_CAPITAL_LETTER_T_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_T_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter u iso-8859-11 character code model. U+0055 */
static char* LATIN_CAPITAL_LETTER_U_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_U_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter v iso-8859-11 character code model. U+0056 */
static char* LATIN_CAPITAL_LETTER_V_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_V_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter w iso-8859-11 character code model. U+0057 */
static char* LATIN_CAPITAL_LETTER_W_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_W_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter x iso-8859-11 character code model. U+0058 */
static char* LATIN_CAPITAL_LETTER_X_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_X_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter y iso-8859-11 character code model. U+0059 */
static char* LATIN_CAPITAL_LETTER_Y_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Y_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin capital letter z iso-8859-11 character code model. U+005A */
static char* LATIN_CAPITAL_LETTER_Z_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_CAPITAL_LETTER_Z_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The left square bracket iso-8859-11 character code model. U+005B */
static char* LEFT_SQUARE_BRACKET_ISO_8859_11_CHARACTER_CODE_MODEL = LEFT_SQUARE_BRACKET_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The reverse solidus iso-8859-11 character code model. U+005C */
static char* REVERSE_SOLIDUS_ISO_8859_11_CHARACTER_CODE_MODEL = REVERSE_SOLIDUS_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The right square bracket iso-8859-11 character code model. U+005D */
static char* RIGHT_SQUARE_BRACKET_ISO_8859_11_CHARACTER_CODE_MODEL = RIGHT_SQUARE_BRACKET_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The circumflex accent iso-8859-11 character code model. U+005E */
static char* CIRCUMFLEX_ACCENT_ISO_8859_11_CHARACTER_CODE_MODEL = CIRCUMFLEX_ACCENT_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The low line iso-8859-11 character code model. U+005F */
static char* LOW_LINE_ISO_8859_11_CHARACTER_CODE_MODEL = LOW_LINE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The grave accent iso-8859-11 character code model. U+0060 */
static char* GRAVE_ACCENT_ISO_8859_11_CHARACTER_CODE_MODEL = GRAVE_ACCENT_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter a iso-8859-11 character code model. U+0061 */
static char* LATIN_SMALL_LETTER_A_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_A_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter b iso-8859-11 character code model. U+0062 */
static char* LATIN_SMALL_LETTER_B_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_B_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter c iso-8859-11 character code model. U+0063 */
static char* LATIN_SMALL_LETTER_C_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_C_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter d iso-8859-11 character code model. U+0064 */
static char* LATIN_SMALL_LETTER_D_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_D_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter e iso-8859-11 character code model. U+0065 */
static char* LATIN_SMALL_LETTER_E_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_E_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter f iso-8859-11 character code model. U+0066 */
static char* LATIN_SMALL_LETTER_F_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_F_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter g iso-8859-11 character code model. U+0067 */
static char* LATIN_SMALL_LETTER_G_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_G_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter h iso-8859-11 character code model. U+0068 */
static char* LATIN_SMALL_LETTER_H_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_H_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter i iso-8859-11 character code model. U+0069 */
static char* LATIN_SMALL_LETTER_I_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_I_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter j iso-8859-11 character code model. U+006A */
static char* LATIN_SMALL_LETTER_J_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_J_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter k iso-8859-11 character code model. U+006B */
static char* LATIN_SMALL_LETTER_K_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_K_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter l iso-8859-11 character code model. U+006C */
static char* LATIN_SMALL_LETTER_L_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_L_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter m iso-8859-11 character code model. U+006D */
static char* LATIN_SMALL_LETTER_M_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_M_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter n iso-8859-11 character code model. U+006E */
static char* LATIN_SMALL_LETTER_N_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_N_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter o iso-8859-11 character code model. U+006F */
static char* LATIN_SMALL_LETTER_O_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_O_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter p iso-8859-11 character code model. U+0070 */
static char* LATIN_SMALL_LETTER_P_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_P_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter q iso-8859-11 character code model. U+0071 */
static char* LATIN_SMALL_LETTER_Q_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Q_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter r iso-8859-11 character code model. U+0072 */
static char* LATIN_SMALL_LETTER_R_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_R_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter s iso-8859-11 character code model. U+0073 */
static char* LATIN_SMALL_LETTER_S_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_S_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter t iso-8859-11 character code model. U+0074 */
static char* LATIN_SMALL_LETTER_T_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_T_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter u iso-8859-11 character code model. U+0075 */
static char* LATIN_SMALL_LETTER_U_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_U_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter v iso-8859-11 character code model. U+0076 */
static char* LATIN_SMALL_LETTER_V_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_V_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter w iso-8859-11 character code model. U+0077 */
static char* LATIN_SMALL_LETTER_W_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_W_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter x iso-8859-11 character code model. U+0078 */
static char* LATIN_SMALL_LETTER_X_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_X_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter y iso-8859-11 character code model. U+0079 */
static char* LATIN_SMALL_LETTER_Y_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Y_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The latin small letter z iso-8859-11 character code model. U+007A */
static char* LATIN_SMALL_LETTER_Z_ISO_8859_11_CHARACTER_CODE_MODEL = LATIN_SMALL_LETTER_Z_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The left curly bracket iso-8859-11 character code model. U+007B */
static char* LEFT_CURLY_BRACKET_ISO_8859_11_CHARACTER_CODE_MODEL = LEFT_CURLY_BRACKET_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The vertical line iso-8859-11 character code model. U+007C */
static char* VERTICAL_LINE_ISO_8859_11_CHARACTER_CODE_MODEL = VERTICAL_LINE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The right curly bracket iso-8859-11 character code model. U+007D */
static char* RIGHT_CURLY_BRACKET_ISO_8859_11_CHARACTER_CODE_MODEL = RIGHT_CURLY_BRACKET_ASCII_CHARACTER_CODE_MODEL_ARRAY;

/** The tilde iso-8859-11 character code model. U+007E */
static char* TILDE_ISO_8859_11_CHARACTER_CODE_MODEL = TILDE_ASCII_CHARACTER_CODE_MODEL_ARRAY;

//
// The non-printable control characters in range 0x7F-0x9F
// are NOT defined, since an "ISO-8859-11" does NOT exist.
//

//
// The printable characters in range 0xA0-0xFF.
//

/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA1    0x0E01  #       THAI CHARACTER KO KAI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA2    0x0E02  #       THAI CHARACTER KHO KHAI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA3    0x0E03  #       THAI CHARACTER KHO KHUAT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA4    0x0E04  #       THAI CHARACTER KHO KHWAI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA5    0x0E05  #       THAI CHARACTER KHO KHON
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA6    0x0E06  #       THAI CHARACTER KHO RAKHANG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA7    0x0E07  #       THAI CHARACTER NGO NGU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA8    0x0E08  #       THAI CHARACTER CHO CHAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xA9    0x0E09  #       THAI CHARACTER CHO CHING
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAA    0x0E0A  #       THAI CHARACTER CHO CHANG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAB    0x0E0B  #       THAI CHARACTER SO SO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAC    0x0E0C  #       THAI CHARACTER CHO CHOE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAD    0x0E0D  #       THAI CHARACTER YO YING
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAE    0x0E0E  #       THAI CHARACTER DO CHADA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xAF    0x0E0F  #       THAI CHARACTER TO PATAK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB0    0x0E10  #       THAI CHARACTER THO THAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB1    0x0E11  #       THAI CHARACTER THO NANGMONTHO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB2    0x0E12  #       THAI CHARACTER THO PHUTHAO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB3    0x0E13  #       THAI CHARACTER NO NEN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB4    0x0E14  #       THAI CHARACTER DO DEK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB5    0x0E15  #       THAI CHARACTER TO TAO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB6    0x0E16  #       THAI CHARACTER THO THUNG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB7    0x0E17  #       THAI CHARACTER THO THAHAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB8    0x0E18  #       THAI CHARACTER THO THONG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xB9    0x0E19  #       THAI CHARACTER NO NU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBA    0x0E1A  #       THAI CHARACTER BO BAIMAI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBB    0x0E1B  #       THAI CHARACTER PO PLA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBC    0x0E1C  #       THAI CHARACTER PHO PHUNG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBD    0x0E1D  #       THAI CHARACTER FO FA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBE    0x0E1E  #       THAI CHARACTER PHO PHAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xBF    0x0E1F  #       THAI CHARACTER FO FAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC0    0x0E20  #       THAI CHARACTER PHO SAMPHAO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC1    0x0E21  #       THAI CHARACTER MO MA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC2    0x0E22  #       THAI CHARACTER YO YAK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC3    0x0E23  #       THAI CHARACTER RO RUA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC4    0x0E24  #       THAI CHARACTER RU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC5    0x0E25  #       THAI CHARACTER LO LING
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC6    0x0E26  #       THAI CHARACTER LU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC7    0x0E27  #       THAI CHARACTER WO WAEN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC8    0x0E28  #       THAI CHARACTER SO SALA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xC9    0x0E29  #       THAI CHARACTER SO RUSI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCA    0x0E2A  #       THAI CHARACTER SO SUA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCB    0x0E2B  #       THAI CHARACTER HO HIP
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCC    0x0E2C  #       THAI CHARACTER LO CHULA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCD    0x0E2D  #       THAI CHARACTER O ANG
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCE    0x0E2E  #       THAI CHARACTER HO NOKHUK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xCF    0x0E2F  #       THAI CHARACTER PAIYANNOI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD0    0x0E30  #       THAI CHARACTER SARA A
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD1    0x0E31  #       THAI CHARACTER MAI HAN-AKAT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD2    0x0E32  #       THAI CHARACTER SARA AA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD3    0x0E33  #       THAI CHARACTER SARA AM
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD4    0x0E34  #       THAI CHARACTER SARA I
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD5    0x0E35  #       THAI CHARACTER SARA II
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD6    0x0E36  #       THAI CHARACTER SARA UE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD7    0x0E37  #       THAI CHARACTER SARA UEE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD8    0x0E38  #       THAI CHARACTER SARA U
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xD9    0x0E39  #       THAI CHARACTER SARA UU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xDA    0x0E3A  #       THAI CHARACTER PHINTHU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xDF    0x0E3F  #       THAI CURRENCY SYMBOL BAHT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE0    0x0E40  #       THAI CHARACTER SARA E
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE1    0x0E41  #       THAI CHARACTER SARA AE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE2    0x0E42  #       THAI CHARACTER SARA O
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE3    0x0E43  #       THAI CHARACTER SARA AI MAIMUAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE4    0x0E44  #       THAI CHARACTER SARA AI MAIMALAI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE5    0x0E45  #       THAI CHARACTER LAKKHANGYAO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE6    0x0E46  #       THAI CHARACTER MAIYAMOK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE7    0x0E47  #       THAI CHARACTER MAITAIKHU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE8    0x0E48  #       THAI CHARACTER MAI EK
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xE9    0x0E49  #       THAI CHARACTER MAI THO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xEA    0x0E4A  #       THAI CHARACTER MAI TRI
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xEB    0x0E4B  #       THAI CHARACTER MAI CHATTAWA
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xEC    0x0E4C  #       THAI CHARACTER THANTHAKHAT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xED    0x0E4D  #       THAI CHARACTER NIKHAHIT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xEE    0x0E4E  #       THAI CHARACTER YAMAKKAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xEF    0x0E4F  #       THAI CHARACTER FONGMAN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF0    0x0E50  #       THAI DIGIT ZERO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF1    0x0E51  #       THAI DIGIT ONE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF2    0x0E52  #       THAI DIGIT TWO
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF3    0x0E53  #       THAI DIGIT THREE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF4    0x0E54  #       THAI DIGIT FOUR
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF5    0x0E55  #       THAI DIGIT FIVE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF6    0x0E56  #       THAI DIGIT SIX
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF7    0x0E57  #       THAI DIGIT SEVEN
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF8    0x0E58  #       THAI DIGIT EIGHT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xF9    0x0E59  #       THAI DIGIT NINE
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xFA    0x0E5A  #       THAI CHARACTER ANGKHANKHU
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

0xFB    0x0E5B  #       THAI CHARACTER KHOMUT
/** The no-break space iso-8859-11 character code model. U+00A0 */
static char NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY[] = {0xA0};
static char* NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL = NO_BREAK_SPACE_ISO_8859_11_CHARACTER_CODE_MODEL_ARRAY;

/* ISO_8859_11_CHARACTER_CODE_MODEL_CONSTANT_SOURCE */
#endif
